### ISSUE TITLE
UnpDialog control does not work within a UnpFormEditor

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#100]
If I try to create a Dialog inside the scrollable area content of a FormEditor - e.g. to replace an alert - I get a compilation error that the dialog must have an xp:key attribute. It clearly does :-(
(angle brackets removed for post)
xc:unpDialog title="Test Data"
            xp:this.facets
                xp:panel xp:key="facet_1"
                    xp:label id="label1" xp:key="facet_1"
                        value="This data is for test purposes only. In your application this request would now be processed and any workflow triggered"
                    /xp:label
                /xp:panel
            /xp:this.facets
        /xc:unpDialog

**Comment by whitemx** [comment]
As far as I can tell this was working, but in testing it I did spot some CSS bugs which I've fixed now.

I've added a demo of how to use the dialog to the EmployeeEdit XPage. To see it in action, open the demo db, go to the All Widgets page and then create a new document, there is a button at the bottom of the screen which will show the dialog.
