### ISSUE TITLE
On an iPad, in landscape mode, the menu overlaps with the Accordion control

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#101]
On an iPad, in landscape mode, the menu overlaps with the Accordion control and there is no way to remove the menu. In portrait mode, everything is ok.
![photo 3 ](https://f.cloud.github.com/assets/3041329/101920/772f6a7c-68fd-11e2-85be-2aadbe16a31b.PNG)

**Comment by whitemx** [comment]
Ady,

Could you send me a copy of the database with this issue please. I'm unable to reproduce the problem in the demo database.

Thanks

Matt
