### ISSUE TITLE
Experiment with lazy loading JQuery plugin

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#106]

**Comment by markleusink** [comment]
This is the plugin I was talking about: http://www.appelsiini.net/projects/lazyload

**Comment by whitemx** [comment]
I spent a few hours today looking at this. For the minor benefit it will offer, there is a lot of work required to implement the change:
- process images on page load
- change iScroll to support lazyload 
- handle ajax loads of pages 

My feeling is that at the moment the performance boost is not worth the effort.
