### ISSUE TITLE
Pager not displaying correct number of items

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#11]

**Comment by whitemx** [comment]
When I show a Swipe view to display 3 attachments, I still see 6 "blobs" to indicate there are six items to be displayed.

**Comment by RichSharpe** [comment]
This is part of the plug-in by Matteo S. We have no plans to branch and maintain this. We will be speaking to Matteo later in the project and can raise this point with him. The extra 'blobs' cycle through existing photos as it is based on a carousel system.
