### ISSUE TITLE
Mobile browsers need to be supported and tested

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#111]
Mobile Safari and Android Chrome browser

**Comment by whitemx** [comment]
I've spent some time looking at this today and so far am at the point where I need to be able to tell where the application is running (i.e. mobile browser vs Unplugged vs Desktop). According to Rich there is no official support to be able to do this at the moment. I can test for the existence of UnpluggedLib:

```
if (null != UnpluggedLib) {
 // Running under unplugged
}
else {
  // Domino server
}
```

But apparently this is not going to work going forwards. 

Waiting for guidance on what the best approach is here.

**Comment by sives** [comment]
Just spoke to Mark on this.  In future (maybe April) we will extend the Unplugged Properties to give some platform specific information which will allow us to take the best decisions on layouts within the Controls.  For now we should just use the undocumented feature that Mark has mentioned to Rich.
