### ISSUE TITLE
Date picker not showing in Unplugged on Android Nexus 7

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#125]
This is a very odd one that I can't tell if it's Unplugged or Android at fault with.

In the demo Employee form, there is a date field which should pop up a native picker when you enter it. This works in iOS (phone and tablet) and Android Phone (Galaxy S3) and even on the Nexus 7 on the web, but in Unplugged it is treated as a plain text field.

The images below are the same screen on the Nexus 7, one in browser and the other in Unplugged with the focus on the DOB field.

Any ideas?

**Comment by whitemx** [comment]
![2013-02-08 08 01 43](https://f.cloud.github.com/assets/856638/138720/f693e6be-71c5-11e2-9525-5f30e439bd14.png)
![2013-02-08 08 01 10](https://f.cloud.github.com/assets/856638/138721/fa6d8178-71c5-11e2-861d-c76bd59da984.png)

**Comment by RichSharpe** [comment]
This is also the case on Nexus phone running Android 4.2.2 - what was the fix?

**Comment by whitemx** [comment]
As far as I can tell this is a bug with Android or Unplugged. I can't fix
it in my level of code.

On 29 April 2013 14:26, Rich Sharpe notifications@github.com wrote:

> This is also the case on Nexus phone running Android 4.2.2
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/125#issuecomment-17166270
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by adnamsale** [comment]
According to most online references, Android has not supported HTML 5 input type="date" elements for the longest time. It looks like they've started to add support in recent versions - I'll see if I can find any references with specifics on which Android versions support it. I'll see if I can find out what's happening on the Nexus 7. It's certainly possible, especially with a new feature, that it's supported in the full browser but not the embedded browser control that Unplugged uses. It's also possible that there may be a new Android API that we need to implement to enable the date picker. So this may be outside of Unplugged's control too, but I'll take a look.

**Comment by whitemx** [comment]
Just as an FYI, it works fine on a Samsung Galaxy SIII (running 4.1.2)
whereas the 4.2 Nexus devices it seems to be broken. Not a massive issue,
just something to be aware of really.

On 29 April 2013 15:04, adnamsale notifications@github.com wrote:

> According to most online references, Android has not supported HTML 5
> input type="date" elements for the longest time. It looks like they've
> started to add support in recent versions - I'll see if I can find any
> references with specifics on which Android versions support it. I'll see if
> I can find out what's happening on the Nexus 7. It's certainly possible,
> especially with a new feature, that it's supported in the full browser but
> not the embedded browser control that Unplugged uses. It's also possible
> that there may be a new Android API that we need to implement to enable the
> date picker. So this may be outside of Unplugged's control too, but I'll
> take a look.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/125#issuecomment-17168364
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
