### ISSUE TITLE
The "Last updated" date/time in the footer control to show last app sync time

### ISSUE THREAD

**Issue by arshadkhalid** [unplugged/unplugged-controls#128]
The "Last updated" date/time in the footer control uses the ro.last.replicate environment var which stores the time since the last sync was done using the Unplugged workspace sync button. This var is not set when a call to the NotesDatabase.replicate is made.
So this should be modified so that each sync button in the footer uses a var for the app it is in to store the last rep time and then use this to show the computed value.

**Comment by whitemx** [comment]
Hi Rich,

Was there any progress on the environment variable change for the last replication time on Android? I may as well kill two birds with one stone if possible.

Matt

**Comment by arshadkhalid** [comment]
Matt - the current var also works on Android. It's just that it stores the date as milliseconds since 1970 whereas on iOS this is stored as text string.
There is going to be a ro.last.sync var in the next version which will store the date as milliseconds on both Android and iOS.

Arshad

**Comment by whitemx** [comment]
So in terms of timing, when will the new variable be available for me to
use? I just don't want to do a bunch of work and then have to re-do it a
couple of weeks later!

Thanks

On 13 February 2013 09:07, Arshad Khalid notifications@github.com wrote:

> Matt - the current var also works on Android. It's just that it stores the
> date as milliseconds since 1970 whereas on iOS this is stored as text
> string.
> There is going to be a ro.last.sync var in the next version which will
> store the date as milliseconds on both Android and iOS.
> 
> Arshad
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/128#issuecomment-13480078.

## 

_Matt White_
Phone - +44 203 287 7187
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by arshadkhalid** [comment]
There is going to be a maintenance release in mid March which should contain this new env var.
However, I think to show the last app sync time, you wouldn't be able to use either of them as they only show the time since the last workspace sync. Wouldn't you need to create an app specific var which would get set under the  footer sync button and then use that in the footer display?

**Comment by whitemx** [comment]
I will need to compare both variables. If the user syncs an individual
database but then goes and syncs all databases I will need to pick up that
latter sync and display it.

On 13 February 2013 09:28, Arshad Khalid notifications@github.com wrote:

> There is going to be a maintenance release in mid March which should
> contain this new env var.
> However, I think to show the last app sync time, you wouldn't be able to
> use either of them as they only show the time since the last workspace
> sync. Wouldn't you need to create an app specific var which would get set
> under the footer sync button and then use that in the footer display?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/128#issuecomment-13480836.

## 

_Matt White_
Phone - +44 203 287 7187
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by arshadkhalid** [comment]
Ah! I see coz you're going to add the ability to sync all dbs from the sync button in the footer!
In that case we'll have to wait for Mark to release the next testflight version. Will ask him when it is due and let you know.

**Comment by arshadkhalid** [comment]
Hi Matt -Mark expects the new var to be part of a 2.2 maintenance release scheduled for mid-March. He's hoping that  he'd be able to do a testflight build by the end of this month.

**Comment by whitemx** [comment]
Latest update from Mark:

"Darn, you're right. We had a last minute change of plan here about releasing 2.3 and not all fixes from the 2.3 code stream made it back to 2.2."

Looks like this will need to wait a while longer.
