### ISSUE TITLE
Change how attachments are accessed in Swipe View

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#13]
Rather than require the Document Data binding to have a specific name, create a custom property where the user passes in the UNID of the document and access it inside the custom control.

**Comment by RichSharpe** [comment]
Currently working with the Unplugged Dev Team to discuss best way to incorporate displaying photos stored by the new camera support

**Comment by RichSharpe** [comment]
This is now fixed in Unplugged - support for getAttachmentList() and getAttachmentList('string'). By default the control takes all images. The restrictions are more to do with the Domino server packet sizes which are explained further in the Unplugged User Guide.
