### ISSUE TITLE
iScroll initializes 5 times on opening 

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#132]
I'm having some issues with the iScroll library in Continuity. I added some console logging to the iScroll initialisation code (initiscroll function in unplugged.js). It turned out that the iScroll object is created multiple times when I open a page (if I open UnpDemoWidgets.xsp for example, both the menu and content iScroll objects are constructed 5 times).

Is this needed? And doesn't that have an impact on the performance?

**Comment by whitemx** [comment]
As far as I can tell iScroll itself modifies the DOM to the extent that the jQuery load event re-fires. Without doing a full re-test of every control (which would take far longer than the time I have available to me) I would be nervous about changing it.
