### ISSUE TITLE
Save and Cancel buttons mangled

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#134]
In the v1.2 Controls "Demo of all Widgets", the colour panels of the Save and Cancel buttons in forms are incorrectly displayed.  The green Save button is juxtaposed right up agains the red Cancel button with no white space left between them.  Looking more closely this seems to be because there are two Green button panels slightly out of alignment stacked on top of each other, and two red panels likewise.

**Comment by whitemx** [comment]
This is a bug introduced by me as part of 1.3 development for the standalone button controls, will get it fixed.
