### ISSUE TITLE
New grey circle feature in v1.2

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#135]
I like your new grey circle feature (and thanks for getting this into 1.2!) but the circle needs to be nearly twice its current diameter.  The diameter should be the same as the height of the largest capitalised text character in the adjacent field.  Also, it should be positioned in proper alignment with the text characters i.e. centre aligned

**Comment by whitemx** [comment]
Hi Steve,

That is still being worked on a little, it didn't make it into 1.2, I had
started work on the 1.3 changes.

Matt

On 28 February 2013 10:15, sives notifications@github.com wrote:

> I like your new grey circle feature (and thanks for getting this into
> 1.2!) but the circle needs to be nearly twice its current diameter. The
> diameter should be the same as the height of the largest capitalised text
> character in the adjacent field. Also, it should be positioned in proper
> alignment with the text characters i.e. centre aligned
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/135
> .

## 

_Matt White_
Phone - +44 203 287 7187
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
