### ISSUE TITLE
Background color is off when using OneUI v2.1

### ISSUE THREAD

**Issue by Stwissel** [unplugged/unplugged-controls#138]
In an multi-mode application (OneUI for desktop, unplugged for mobile) the (background) color goes from gray to white when the OneUI v2.1 is used. Some CSS magic needed

**Comment by whitemx** [comment]
A few questions...

Are you using the Unplugged Controls on a mobile browser or via Teamstudio Unplugged App?

If via a mobile browser, how are you switching between "mobile mode" and "desktop mode"?

If via Teamstudio Unplugged, which device are you using?

Thanks

Matt

**Comment by Stwissel** [comment]
I tried it first on a desktop, didn't test it in mobile yet. Btw. the behavior is consistent with the IBM mobile controls: they look dark (Android style) in OneUI v2.0 but loose their background color in OneUI v2.1 - I'm on a 9.0 server
