### ISSUE TITLE
Labels in UnpFormView control give 'jagged' look (too tall)

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#139]
In the latest build the labels are too tall. I think I tracked it down to the CSS (line 1323) #formholder label. The padding needs to be 10px not 12px for the top.

**Comment by whitemx** [comment]
Could you give me a screenshot of the problem? I changed that particular line as Steve logged #136 that the labels weren't aligned properly.

Thanks

Matt

**Comment by whitemx** [comment]
I think this one is fixed so closing.
