### ISSUE TITLE
Priorities for v1.4

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#147]
Matt, 
Here are my priorities for v1.4:
- A Control that mimics Mark Leusink's main Contacts view in Continuity
  (containing avatar thumbnails, with blue separator panels, please also if possible add A - Z selector on right hand side - implemented like the one in Apple's own Contacts app on the iPhone - to allow rapid navigation to a specific letter of the alphabet in longer lists)
- Extend some of our current Controls (or create new ones) to allow standard rendering of the main Views in other key screens in Continuity (Call Tree, Incidents, My Role, Plans, Active Tasks, Updates

Note that the My Role view supports up to 2 lines of text in the primary text field, rather than just 1 line with auto-truncation.  This is a key requirement, to make the view easy to understand and use on a smartphone screen.  We also need a header panel stacked on top of the view elements panel.  This is needed so that we can put a label at the top of the view elements to explain what they are, in this case "Responsibilities".
- Version number dialog on Header bar
- Fix the search bug(s) that Rich mentioned in our call
- if time allows, a Control for type-ahead look-ups for Form elements)

**Comment by whitemx** [comment]
I have split this item out into individual Issues.
