### ISSUE TITLE
Unplugged client freezes after going into Database Search

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#160]
This was on my iPhone 5.   Unplugged client became unresponsive, even after exiting the app and re-entering.  Had to delete Unplugged app and re-install.  Ouch.

**Comment by whitemx** [comment]
I'm unable to reproduce this issue. Tested on iPhone 4S, iPad3, Nexus7, Galaxy SIII. Any further details would be great.

**Comment by whitemx** [comment]
Not had this re-occur so closing. We can re-open if it happens again.
