### ISSUE TITLE
Employee form - edit mode - label alignment

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#171]
In Demo of All Widgets, in the Employee form edit mode the field item text needs to be precisely bottom-aligned in the vertical dimension with the field label text.  At the moment it looks to be one or two pixels too high on my iPhone 5, to my eye.  Also, the grey circle with a cross in it is one or two pixels too high. (this is a very cosmetic issue, just being a perfectionist!)

**Comment by whitemx** [comment]
![photo](https://f.cloud.github.com/assets/856638/424565/fc76c052-ad8d-11e2-8293-58cf81af9413.PNG)
Demo of fixed alignment in iPhone 4S

**Comment by sives** [comment]
Not quite.   

The word "Test" should be bottom aligned with the field label "Name".   It looks as if it is one or two pixels above the field label (maybe it is just my eyes!)

The grey circle should be centred  in the vertical dimension within the rectangular box so the white space above the circle is the same pixel count as the white space belwo the grey circle.

**Comment by whitemx** [comment]
The label and text in the field are exactly aligned, it maybe looks misaligned due to the different fonts / colors / sizes of the two elements.

The cross icon was 1 pixel out and has been fixed now.
