### ISSUE TITLE
Allow UnpNavigator to include programatic entries

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#180]
Currently if I enter a programatic value in the 'page' custom property field the source give 'undefined' as the url entry.

**Comment by RichSharpe** [comment]
Not sure if this is required now that a tabbed footer can be used??

**Comment by whitemx** [comment]
I tested this and it seems to work fine for me. Have you got any more details?

**Comment by whitemx** [comment]
As of 1.6 the menu items in the navigator can be completely computed using the new custom property "computedmenuitems"
