### ISSUE TITLE
Header bar event sensing

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#183]
When you tap on buttons located in the Header bar (e.g. the View picker or the Search button) there is a noticeable latency before anything happens.  It would be nice if you could register the tap event immediately e.g. with a fade-out of the button and then complete the button action (as already happens with other Unplugged Controls actions).

**Comment by whitemx** [comment]
There really shouldn't be any latency, I will have a look to see what is
happening.

Could you provide a little more detail of the device being used and the
application which you're seeing the slow response on?

Thanks

Matt

On 9 May 2013 22:42, sives notifications@github.com wrote:

> When you tap on buttons located in the Header bar (e.g. the View picker or
> the Search button) there is a noticeable latency before anything happens.
> It would be nice if you could register the tap event immediately e.g. with
> a fade-out of the button and then complete the button action (as already
> happens with other Unplugged Controls actions).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/183
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by sives** [comment]
It's on my iPhone 5 and in your 1.4 Unplugged Controls Library, Demo of All Widgets.

Sometimes the iPhone screen sensor mechanism fails to register a touch event if you touch very close to the edge and/or top of the screen (nothing to do with Unplugged) and the user needs to touch again.   

This causes a double confusion for the user if there is any latency in the header bar.  The user wonders if the lack of response is due to the iPhone screen sensing or the latency within the Unplugged header bar.

**Comment by RichSharpe** [comment]
I'm not experiencing this on iOS 5, Unplugged 2.4, Controls 1.4 - the search and the navigation list are almost instant.

**Comment by unplugged** [comment]
OK, let's hold off on this until I meet up with Matt White in London next week
