### ISSUE TITLE
The  Navigator is not displayed

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#185]
I am testing UnpDemoWidgets XPage in the version 1.4 of the Custom Controls and for some reason the navigator is not displayed. 

I am currently using Unplugged 2.4 on an iPad but I got exactly the same result with Unplugged 2.2. Even when I display the XPage in Chrome I get the same result... 

![photo](https://f.cloud.github.com/assets/3041329/495913/d237f2c0-bbd4-11e2-8f81-745ce938a285.png)

**Comment by whitemx** [comment]
Hi Ady

Which server are you syncing with? I am doing a load of development today
which may have broken things for you!

Matt

On 13 May 2013 14:58, AdyMakombo notifications@github.com wrote:

> I am testing UnpDemoWidgets XPage in the version 1.4 of the Custom
> Controls and for some reason the navigator is not displayed.
> 
> I am currently using Unplugged 2.4 on an iPad but I got exactly the same
> result with Unplugged 2.2. Even when I display the XPage in Chrome I get
> the same result...
> 
> [image: photo]https://f.cloud.github.com/assets/3041329/495913/d237f2c0-bbd4-11e2-8f81-745ce938a285.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/185
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by AdyMakombo** [comment]
Hi,

I am using http://unpluggeddev.teamstudio.com/

BTW, I noticed the problem starting last Friday when I was using Unplugged 2.2. I upgraded to 2.4 today hoping that it would help...

Ady

**Comment by AdyMakombo** [comment]
FYI... I downloaded this db from OpenNTF last Friday (May 10th). I just renamed the .NSF file...

Ady

**Comment by whitemx** [comment]
I'm not seeing that behaviour. Tested on iPad 3, iPhone 4S, Nexus 7 and
Galaxy SIII.

I think there's an internal test server run by Rich Sharpe (I don't have
access to any of the internal stuff unfortunately). Could you check to see
if that has the same problem?

On 14 May 2013 08:22, AdyMakombo notifications@github.com wrote:

> FYI... I downloaded this db from OpenNTF last Friday (May 10th). I just
> renamed the .NSF file...
> 
> Ady
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/185#issuecomment-17860567
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by whitemx** [comment]
Fixed (along with a bunch of other minor issues) as part of 1.4.1. Problems related to the release of Unplugged 2.4.
