### ISSUE TITLE
Allow for relative links in unpWorkspace

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#188]
The demo application has a set of HomeLink documents that point to a fixed path (unplugged/UnpluggedCustomControlsLibrary.nsf). If I install the application in a different location or with a different filename, the demo application doesn't work. I'm not sure if this is documented somewhere, but most users won't probably read much documentation.

If you add the option that a HomeLink can point to a page in the current database, the demo application will always keep working, independent of its location.

**Comment by whitemx** [comment]
The workspace needs to support opening links in other databases, so I've updated the view which holds the workspace items to handle relative links rather than the control itself.
