### ISSUE TITLE
Categories in unpFlatView aren't rendered correctly in Unplugged 2.4

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#190]
Example: UnpDemoWidgetsByDept (Demo of all widgets > Employees by department).

Reason is that since 2.4 a disableTheme="true" will complete disable all HTML tags (only text is rendered).

Fix: add an 'id' attribute to the xp:text control and remove the disableTheme attribute.

**Comment by whitemx** [comment]
This should be fixed already in the 1.4.1 release which is being tested by
Arshad at the moment.

On 16 May 2013 10:51, Mark Leusink notifications@github.com wrote:

> Example: UnpDemoWidgetsByDept (Demo of all widgets > Employees by
> department).
> 
> Reason is that since 2.4 a disableTheme="true" will complete disable all
> HTML tags (only text is rendered).
> 
> Fix: add an 'id' attribute to the xp:text control and remove the
> disableTheme attribute.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/190
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
