### ISSUE TITLE
Unplugged controls and Continuity

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#192]
ISSUES
- In the accordion view (UnpDemoAccordion.xsp), if there's only 1 category the rounded borders at the bottom are missing (see screenshot). 
- The navigation flow of the demo application is not always logical. Examples:
  - The "Back" button on an employee, always takes me back to the Unplugged Workspace.
  - Same for the "Back" button in UnpDemoHeaderFooterBackButton.xsp
  - The "Home" button always opens the Unplugged Workspace, I expected it to take me back to the demo app's main page. Idea: on UnpMain add an 'exit' button and let the Home button always point to the app's main page.
- The "Flat View (different database)" is the first link in the sample database, but if a user doesn't have the Teamroom application installed (at an exact location: teamstudio/widgets/Teamroom.nsf), it will throw an error. User's that check out the control will probably never have that database and instantly have an error. For a better 'first-time' experience I think it would be better to find another solution for an examples link to a different database (or check first if the database is present at all).

MISSING FOR CONTINUITY

I found the following issues when doing research for using the controls for Continuity. Even with these functions added (if possible), I have doubts in whether it will be possible to completely re-built Continuity with the controls without making any concessions to the current functionality. For performance enhancements I also removed code I didn't use (Unplugged still needs time to process code with rendered set to false).
- The views/ lists only allow for 2 lines of text. The Contacts view in Continuity uses 3, of which the last is color coded based on its value.
- In the call tree I've added a button to instantly call a person from the list (only if the device is phone-capable - and that can be detected).
- Disabled items on the workspace (unpWorkspace)
- Disabled menu items in unpNavigator
- The Incidents view (accordion) needs an option to (on opening) show the first category opened.
- The Task lists in Continuity have 2 levels of (fixed) categorization and allow (besides expanding/ collapsing) for:
  - marking a task as done/ not done using a checkbox
  - adding a link to a 'quick guide'
- The Updates view in Continuity has an icon as well as (HTML) content.

![screen1](https://f.cloud.github.com/assets/1773707/554947/ff58f92e-c3b4-11e2-8993-db796162c1d1.png)

**Comment by markleusink** [comment]
Fix for the accordion not having rounded borders (clientside): add this to the accordionLoadMore function.

$(thisArea).append($(".summaryDataRow li"));

//check if there's only 1 expanded category and set a class to create a rounded bottom border
if ( $("#summaryList .categoryrow").length == 1 ) {
  $("#summaryList div.summaryDataRow ul.accordionRowSet li:last-child").addClass("roundedBottom");
}

**Comment by whitemx** [comment]
I've split this out into #193, #194, #195, #196, #197, #198, #199, #200, #201, #202 so that each item can be tracked individually.
