### ISSUE TITLE
New Unplugged Logo available

### ISSUE THREAD

**Issue by adnamsale** [unplugged/unplugged-controls#209]
Hi Matt,

We recently updated the Unplugged icon and logo and it would be nice to get the new logo
 into the controls at some point. I only recall seeing it in the header, top left. 

I've attached the version I have of the logo - let me know if you need it in a different size/format etc. Also, if the Unplugged icon is used anywhere then I can get you a new version of that.

Thanks!
Mark

![unplugged_logo_3inch_72dpi_rgb_transparent](https://f.cloud.github.com/assets/2934599/560229/824757fa-c46d-11e2-97e0-2c2b7a78f3bb.png)

**Comment by whitemx** [comment]
Hi Mark,

Thanks. Arshad had already sent me the new icon and it's included in the
next version of the controls.

Matt

On 24 May 2013 13:32, adnamsale notifications@github.com wrote:

> Hi Matt,
> 
> We recently updated the Unplugged icon and logo and it would be nice to
> get the new logo
> into the controls at some point. I only recall seeing it in the header,
> top left.
> 
> I've attached the version I have of the logo - let me know if you need it
> in a different size/format etc. Also, if the Unplugged icon is used
> anywhere then I can get you a new version of that.
> 
> Thanks!
> Mark
> 
> [image: unplugged_logo_3inch_72dpi_rgb_transparent]https://f.cloud.github.com/assets/2934599/560229/824757fa-c46d-11e2-97e0-2c2b7a78f3bb.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/209
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
