### ISSUE TITLE
UnpFormViewer missing rounded corners at bottom

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#221]
If the labels & fields are added placed inside a panel (as shown in the wiki documentation & Rich's video) then the containing panel has rounded corners at the top and square corners at the bottom. Should be the same top & bottom?

If the labels and fields are wrapped in an unordered list (as in the demo app) then the panel has rounded corners top and bottom.

**Comment by whitemx** [comment]
Thanks for reporting this, I have updated the wiki, the correct markup is: 

``` xml
<xc:unpFormViewer showbuttons="true"
    closexpagename="UnpDemoWidgets.xsp" editxpagename="EmployeeEdit.xsp"
    formname="Employee" title="Employee"
    newresponsexpagename="EmployeeEdit.xsp">
    <xp:this.facets>
        <xp:panel xp:key="facet_1">
            <ul class="fieldlist">
                <li>
                    <xp:label value="Name" id="namelabel"
                        for="name">
                    </xp:label>
                    <xp:text id="name" value="#{document1.Name}"></xp:text>
                </li>
            </ul>
        </xp:panel>
    </xp:this.facets>
</xc:unpFormViewer>
```
