### ISSUE TITLE
UnpFormEditor - "viewxpagename" is ignored

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#223]
unplugged.js -  saveDocument  - lines 195 - 199 are commented out. Line 201 has a hard-coded "UnpMain.xsp". This means that whatever is specified for "viewxpagename" is ignored and UnpMain is always displayed.

**Comment by whitemx** [comment]
At the moment this is correct. The "viewxpagename" property is not currently used. I've updated the Wiki to reflect this.
