### ISSUE TITLE
UnpFormEditor - question on use of "closexpagename"

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#224]
Not sure if you view this as a bug or "functioning as designed"!

unpFormEditor.xsp - "closebutton" panel. The onclick event uses the code when the Cancel button is selected :-
    $.blockUI(); window.location.href='" + compositeData.closexpagename + "';"

This works fine is you want to return to say UnpMain, or another page displaying a view. But if I use this to return to the same document in view mode, so I compute the "closexpagename" as, e.g.
    "MyDocumentViewXPage.xsp?action=openDocument&documentId=" + document1.getDocument().getUniversalID();

then the document is displayed out of context without any formatting. Should the code for the onclick event actually be :-
    $.blockUI(); openDocument('" + compositeData.closexpagename + "', 'content')

One other point. When the "closexpagename" is computed it causes an error in the Design Definition for the custom control.

**Comment by whitemx** [comment]
At the moment we need to force the full page refresh when closing a document. I've updated the Wiki to reflect this.
