### ISSUE TITLE
Disabled Workspace icon

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#229]
When you open up the Unplugged Controls workspace, there is a greyed-out icon labelled "Disabled Workspace Icon".  Is this deliberate, to show how to implement a disabled icon, or is it a bug?

If it is deliberate, then the icon background panel should be made a slightly darker shade of grey compared to what it is now, and the icon label text changed from white to light grey.  At the moment it looks like a super-enabled workspace icon, rather than a disabled one - it's so much brighter than a normal icon.

**Comment by whitemx** [comment]
The disabled button is there to show how to implement the disable button. 

I will update the icon shading as part of 1.7.
