### ISSUE TITLE
Flat view form inconsistency

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#231]
When you tap on an item in the Flat View, you get to a form that has no buttons at the top to exit the form.   In the Demo of All Widgets, the form has an Edit button and a Close button at the top.  For consistency, I suggest we do the same in the form in the Flat View.  This also applies to forms in Flat View (Categorised) and Flat View (Different Database).

**Comment by whitemx** [comment]
Moving to v1.7 as we do not have time to deal with this in 1.6
