### ISSUE TITLE
Horizontal Scroller momentum behaviour

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#235]
When you swipe left and right on the rows of items, the momentum behaviour is inconsistent with scrolling in the vertical dimension.

If you scroll Unplugged controls e.g. the Flat View in the vertical dimension, you get just the right degree of momentum effect (by momentum, I mean the tendency of the view to continue scrolling once you take your finger off the screen).

The momentum effect should be similar in both the vertical and the horizontal dimensions.

**Comment by whitemx** [comment]
I've upgraded the control we use for the horizontal scroller so that it better supports momentum. 

It is worth noting that in the iTunes app on the iPad the horizontal momentum is far less than the vertical.
