### ISSUE TITLE
Database search on iPhone

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#240]
Not quite sure why we need the Previous, Next and Done buttons at the top of the keyboard panel on the iPhone version.  I can't seem to trigger any user scenario which needs these buttons, but maybe I'm just being stupid.....

**Comment by whitemx** [comment]
Unfortunately this is not possible, the keyboard is native to the iPhone and I have no control over it.

**Comment by sives** [comment]
This is the appearance of the buttons sitting on top of the keyboard.  I thought the developer could select the type of keyboard that got displayed.  I don't normally see these buttons on top of other iPhone keyboards.

![keyboard pic](https://f.cloud.github.com/assets/2330529/705959/b491e7d4-dde0-11e2-981e-5aa85448df28.png)

**Comment by whitemx** [comment]
I get the ability to control the type of keyboard; text, number, email, etc but I can't control the "Form assistance" bar at the top of the keyboard, that is placed there by iOS. You'll see this bar at the top of keyboards inside Mobile Safari or the embedded browser inside Unplugged.
