### ISSUE TITLE
Footer tab icon spacing on iPhone

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#243]
The spacing rule for icons in footer tabs isn't working properly on the iPhone when using in portrait mode.  It's fine in landscape mode.

There is too much blank space left between the icons and the icon labels in the horizontal dimension.  This means that the left hand icon is getting pushed up right against the Sync button at the left hand side of the footer bar.

SImple solution: just reduce the amount of spacing between these icons in the portrait mode.  

Also, when in landscape mode the Sync update message is overlapping with the Footer tab icons, so I suggest we remove this message completely in both portrait and landscape modes when using Footer Tabs on the iPhone.

**Comment by whitemx** [comment]
This is what I am seeing on the iPhone, not sure I understand what you're after.

![photo](https://f.cloud.github.com/assets/856638/703297/893c12e6-dda7-11e2-80e0-1f8121a83954.png)
![photo 1](https://f.cloud.github.com/assets/856638/703299/8e574886-dda7-11e2-906f-ea6c8ff0a77a.png)

**Comment by sives** [comment]
Here's a screenshot showing the issue.  You've got to have at least 3 footer tabs to see it.

![photo](https://f.cloud.github.com/assets/2330529/818445/64267ade-ef93-11e2-9c06-3b51a331a501.PNG)
