### ISSUE TITLE
Back button on iPad and iPhone

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#244]
The Back button in the Header Bar should not be just a simple rectangular button, but should have an arrow-style treatment, see image below:

![back button](https://f.cloud.github.com/assets/2330529/702016/d518f804-dd85-11e2-8e0a-8b276e084e63.png)

**Comment by whitemx** [comment]
The embedded browser does not render the button correctly so this will take more time than is available in 1.6
