### ISSUE TITLE
Horizontal Scroller - losing items when you swipe

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#247]
When you swipe a row of icons from left to right, the icons eventually disappear completely from view.  It's not then obvious to the user how to get them back if they have been swiped a long way to the left.   

Ideally the row of icons should stop scrolling horizontally once the last icon only is visible, and ideally there should be some kind of elastic bounce effect as the user tries to drag further to the left.

**Comment by whitemx** [comment]
This has been fixed in the latest build.
