### ISSUE TITLE
Header bar tablet version bug

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#26]
When you view the Unplugged Widgets examples on my iPad 1 with iOS 5.1.1, in landscape mode you do not see the Views by default (as you should, according to the spec).   You have to tap on the Views button on the Header bar to bring in the Views nav panel.

Also, in landscape mode the Views button seems to be overlaid on top of the Unplugged logo at the left hand side of the Header bar.  You can just see the left hand edge of the logo and the right hand edge poking out from behind the Views button.

(I will email screen shots to you)

**Comment by whitemx** [comment]
Issue seems to have been against an earlier build of the control and is no longer present.
