### ISSUE TITLE
White flash when changing orientation

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#27]
(Raised by Steve)

There is a screen white flash across the right hand view panel when changing from landscape to portrait mode, and from portrait to landscape mode.

**Comment by whitemx** [comment]
I am not currently seeing this in iPad3. Will continue to investigate.

**Comment by whitemx** [comment]
This appears more as a black flash for me, but I think it is related to this issue: http://cubiq.org/you-shall-not-flicker Will need to test fix with large data sets to make sure it doesn't cause crashes.

The fix is to add -webkit-transform:translate3d(0,0,0); to the definition of #flatViewRowSet>li in the unplugged.css

**Comment by whitemx** [comment]
Steve,

I've added a fix for this issue, but it results in a lag when switching orientation. This lag will get worse the more rows of data are displayed on the screen. Please advise whether you'd like me to retain the fix or revert to the flickering issue.

Matt

**Comment by unplugged** [comment]
Matt, you're right, it is more of a black flash now that I look at it again

On 5 Dec 2012, at 09:37, Matt White wrote:

> This appears more as a black flash for me, but I think it is related to this issue: http://cubiq.org/you-shall-not-flicker Will need to test fix with large data sets to make sure it doesn't cause crashes.
> 
> —
> Reply to this email directly or view it on GitHub.

Steve Ives
stephen.ives@gmail.com

**Comment by whitemx** [comment]
The question is whether the fix I've put in is acceptable in terms of performance when changing orientation.

**Comment by sives** [comment]
Yes, nice, the fix is acceptable performance-wise, let's go with it
