### ISSUE TITLE
Auto-fill in forms is a bit confusing when you first use it

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#270]
When I go down the form filling in "Test" for each text box, and enter "Test" for the Dept field, an auto-fill box appears below the text field with the word "Test" in it.  However, it doesn't look like an auto-fill box at first glance, it looks like a bug, a duplicate of the text box I'm typing in.  

Can we draw a darker or thicker grey line around the auto-fill selector object, to make it clear that it is a selector object? Or some other way to differentiate it, such as offsetting the autofill selector to the right a bit?

In my brief testing, Auto-fill only seems to work in certain fields.  Is this because this feature is word-specific and field-specific i.e. the form has to have seen that word in that specific field before, before it offers it as an auto-fill option?

**Comment by whitemx** [comment]
The auto complete has to be enabled for specific fields (code has to be written to define where the type ahead options are coming from). In this case I have just enabled the Dept field for testing purposes.
