### ISSUE TITLE
Can we add a little more spacing to the AZ picker letters on a phone

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#271]
There is enough space to extend this a little and give the user a bit more room to tap.

**Comment by whitemx** [comment]
Which device is this for? On an iPhone 4 there is no room left at all.

**Comment by RichSharpe** [comment]
hmmmm iPhone 5

**Comment by sives** [comment]
Why not just size if for the iPhone 5?  The feature is useful if it is correctly spaced so you can get your finger on it (i.e. on an iPhone 5) but not very useful if it is squeezed too tight (i.e. on an iPhone 4)

**Comment by whitemx** [comment]
But if it is spaced out any more then it won't fit on the iPhone 4. So do I hide it from that screen?

**Comment by sives** [comment]
As long as its an optional feature or a feature that auto-hides on a small screen, I don't care that it doesn't work on an iPhone 4.  In a way, it's a good thing that it won't work on an iPhone 4, gives users more reason to upgrade to a decent handset that runs Unplugged faster

**Comment by whitemx** [comment]
I've pushed up a change which I think improves things but I don't have an iPhone 5 to test on.
