### ISSUE TITLE
AZ Picker still displays when doc is selected from view

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#273]
The AZ Picker should disappear when a doc/formViewer is displayed

**Comment by sives** [comment]
These feature requests all assume little or zero impact on performance of the view control.  If it causes a performance impact then it's more trouble than it's worth and we should drop it

**Comment by whitemx** [comment]
Agreed. Also assuming that enhancements will be pushed to 1.7 and bug will
be dealt with in 1.6.

**Comment by sives** [comment]
Sounds good to me

**Comment by whitemx** [comment]
I can't reproduce this one. Tested on iOS and Android. Could you let me know how you managed to get this to break?

Thanks

**Comment by RichSharpe** [comment]
Grrr - dragged in a UnpAZPicker Control and Designer 'chose' to put it somewhere else :-( typical.
OK - Once in the 'content' div it displays correctly.
