### ISSUE TITLE
UnpAccordion - left align with no UnpNavigation control displays incorrectly

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#275]
The UnpAccordion Control hangs off the left of the screen on an iPad2 in landscape when set to left-aligned. See screenshot:
![screen shot 2013-07-18 at 1 42 27 pm](https://f.cloud.github.com/assets/2675334/820995/b999d2fc-efd1-11e2-85cd-7ca78bbc9395.png)

**Comment by whitemx** [comment]
I added the "left-aligned" class to the content div in the demo accordion page, that seems to work fine for me.

**Comment by RichSharpe** [comment]
This is a workaround but if you use this control in another app the same things occurs.
