### ISSUE TITLE
Speed up view loading

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#28]
It is taking between 3 and 4 seconds to switch between different views on my iPad, would be nice if we could speed this up a bit if at all possible.
On my iPhone 5 its taking just over 2 seconds to switch, again it would be nice if we could get it a bit faster.

**Comment by whitemx** [comment]
(Raised by Steve)

**Comment by whitemx** [comment]
This is going to be an ongoing task where we make small steps forwards.

A lot of the improvement work done here will be database specific. So for example I shaved 0.5 second load time in the Teamroom by optimizing the view designs.

I have also consolidated the CSS files into a single file which can save up to a second for large page loads!

**Comment by whitemx** [comment]
Removing the icon image files from the database dramatically speeds things up.

**Comment by sives** [comment]
Which icons do you mean exactly?

**Comment by sives** [comment]
Can we leave this issue as an open issue rather than a closed issue please?  It is super-crucial, and we may be able to get Mark Dixon to do some neat optimisations e.g. to address the icon image graphics loading

**Comment by whitemx** [comment]
The icons I was referring to were the image resources which I had included in the database design. As soon as I removed them the teamroom especially speeded up.

**Comment by whitemx** [comment]
Latest Performance Stats: http://teamstudio.s3.amazonaws.com/Timing%20Measurements.pdf

**Comment by whitemx** [comment]
The slow times for saving have now been fixed. So saving averages one second now rather than 3 seconds.
