### ISSUE TITLE
The Back button not displayed in landscape mode

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#283]
On an iPad, the Back button is displayed correctly in portrait mode but the Unplugged logo is displayed instead in landscape mode. I see the same behavior in v1.4.1a and v1.6.0

**Comment by whitemx** [comment]
This is working as designed. The thinking is that the navigator or the Home
button should do everything that the Back button will do. The Back button
is there just for Phone devices.

On 7 August 2013 10:26, AdyMakombo notifications@github.com wrote:

> On an iPad, the Back button is displayed correctly in portrait mode but
> the Unplugged logo is displayed instead in landscape mode. I see the same
> behavior in v1.4.1a and v1.6.0
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/283
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by AdyMakombo** [comment]
I get your point but in this case, to be consistent, on an iPad, shouldn't we display the Unplugged logo in both portrait and landscape modes?

**Comment by whitemx** [comment]
The problem is that the Logo would never show and Steve wanted it to always
show on the iPad in landscape mode (which is considered the primary mode).

I'll raise it with Steve in our next meeting next week.

Matt

**Comment by whitemx** [comment]
This is being superseded by #293
