### ISSUE TITLE
Searching for Double-byte chars (Japanese) doesn't work

### ISSUE THREAD

**Issue by katoman** [unplugged/unplugged-controls#285]
Created a new Employee doc with the Japanese chars and try searching the name.
![search_my_japanese_name](https://f.cloud.github.com/assets/1610383/1023942/aa07fdfe-0e13-11e3-8140-23bbfec0fbd3.png)

The result: Seems like double-byte characters are internally converted into a different string for the search.

![search_result](https://f.cloud.github.com/assets/1610383/1023953/125ab1a8-0e14-11e3-901c-ffa0bcbe1d82.png)

Any workaround or suggestion to fix the problem?

**Comment by sives** [comment]
This is quite important to fix - I'm keen that the Controls support double-byte characters properly
