### ISSUE TITLE
Demo of all widgets issue

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#299]
Go into Demo of all Widgets Control.
Tap on the "New" item button at the bottom right.
Then tap on the "Open Demo Dialog" button - it works OK.
Then tap onto the Details field of the form, opening the on-screen keyboard.
Then tap the "Open Demo Dialog" button again.
The dialog box doesn't display properly - the Footer bar is positioned right in the middle of the screen.

**Comment by whitemx** [comment]
This will take at least one day to fix. Pushing to 2.0.
