### ISSUE TITLE
Viewing data from different database

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#304]
I have a problem with showing data from different databases  in my unpmain i have a accoordian:

```
<unp:unpAccordion xp:key="facet_1"
                viewName="#{javascript:sessionScope.mainSource}"
                xpage="/UnpViewVisit.xsp" insetData="true" expandfirstcategory="no"
                ajaxload="Yes" dbName="unplugged/unp-controls-mp.nsf">
            </unp:unpAccordion>
```

it shows all data  i want it to show but when i click it  it will be sent to the other xpage unpViewVisit.xsp:

```
<unp:unpFormViewer showbuttons="true" editxpagewithajax="no"
            position="menu-aligned" xp:key="facet_1"
            editxpagename="UnpEditVisit.xsp" formname="formVisit" title="Besøg"
            closexpagename="UnpMain.xsp"
            pictureviewpagename="UnpViewPictures.xsp"
            dbName="unplugged/unp-controls-mp.nsf">
```

but then none of the fields are filled with any information

i tested this on the same db and it worked perfectly. 

Hope to get some feedback on this

**Comment by arshadkhalid** [comment]
Hi there - did you remove all the "1s" from the item id attributes in the XPage? For example, for a field named "Name" the item markup should look like this:
<xp:text value="#{document1.Name}" id="name">/xp:text

**Comment by Florenze** [comment]
Im using the same markup as when i had it working using one db like:
< xp:text id="cVisitType_fi"
                                    value="#{document1.cVisitType_fi}">
                                /xp:text

**Comment by whitemx** [comment]
The Controls do not currently support viewing data from another database in the Form controls. You will need to open a page which is stored in the same database as the data.

**Comment by RichSharpe** [comment]
As Matt stated, although the Controls work on Mobile Web XPages as well as Unplugged, they are still limited by the functionality of Unplugged. To achieve what you want, add the XPage into the other DB and then sync that DB over (you can hide this from the workspace if you are using Unplugged by checking the 'Do not show on XPage Workspace' option in the Profile doc). The XPage view DS can access the other DB and then the XPage in the other DB will open.
