### ISSUE TITLE
How to validate ?

### ISSUE THREAD

**Issue by BentPLarsen** [unplugged/unplugged-controls#305]
I have just been introduced to unplugged-controls by Arshad Khalid I have following question to Matt White.
1) How to validate ?, I can't find example. I have tried client and server validation with an display error  control, I can't save, but no messages is shown.I am using 1.6 and IPAD 1., V5.1 + Iphone 4S  6.1.3 
2) No Done/OK button on date picker only for Ipad - have to click outside picker. Maybe because is an old IOS version ?

**Comment by whitemx** [comment]
Hi,

As per the documentation in the Wiki:
https://github.com/unplugged/unplugged-controls/wiki/Unpformeditor

"If you want the field to be mandatory, add a styleClass property of
"required"."

The date picker is native to whatever device you are using, we have no
control over it.

Matt

On 9 September 2013 11:03, BentPLarsen notifications@github.com wrote:

> I have just been introduced to unplugged-controls by Arshad Khalid I have
> following question to Matt White.
> 1) How to validate ?, I can't find example. I have tried client and server
> validation with an display error control, I can't save, but no messages is
> shown.I am using 1.6 and IPAD 1., V5.1 + Iphone 4S 6.1.3
> 2) No Done/OK button on date picker only for Ipad - have to click outside
> picker. Maybe because is an old IOS version ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/305
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
