### ISSUE TITLE
Making a SwipeView control

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#306]
We are having trouble getting SwipeView to work and we want to know if we are using the right tools. 
The swipeview control 
with this Script lib:
https://github.com/unplugged/unplugged-controls/blob/master/Resources/Files/unp_2fidangerous.swiper-2.0.js

we tried using this Script lib:
https://github.com/unplugged/unplugged-controls/blob/2a62ff8a47cdb81ac40f9ac854a6a9b1f513899d/Resources/Files/unp_2fswipeview.js 

but it was old and we couldn't get it to compile because of syntax error on line 187

i hope you will update the swipeview control documentation soon

**Comment by whitemx** [comment]
If you go to the demo database, and look at the "Swipe View" demo, open the first or third documents in the view and you will see the swipe view control in action.

To see how this works, the XPage you want to look at is:
UnpDemoSwipeView - for the view of documents
UnpDemoSwipeViewImages - for the swipe view itself.

You should not need to add any special resources yourself other than unplugged.css
