### ISSUE TITLE
Custom control unpFormViewer has a dbName property that is not used

### ISSUE THREAD

**Issue by ghost** [unplugged/unplugged-controls#308]
In the custom control unpFormViewer a custom property is defined to set (apparently) the target db name to get the document from (dbName), but it isn't used at all in the cc. 

AFAIK Unplugged currently doesn't have a feature to get a document data source from a separate database.

**Comment by markleusink** [comment]
(I was logged in with the wrong account, it is I, Mark L, that created this issue)

**Comment by whitemx** [comment]
Hi Mark,

The property is there but redundant at the moment, the plan is that it will
be supported in future. Hopefully in the 3.0 codestream.

(ML: remove email footer)

**Comment by whitemx** [comment]
I've now added full support to FormViewer and FormEditor for binding onto documents in other databases
