### ISSUE TITLE
Is it possible to have calculated image size in swipeviews?

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#309]
I was wondering if you had any tips for making images with different resolution look good in swipeview on different devices? or is it not possible yet?

**Comment by whitemx** [comment]
In the latest version the images are set to have a maximum size of 95% of
the screen width and height. If they are smaller they won't scale up but
you can change this if you like.

The file you're interested in is called unpSwipeView.css and the definition
of #swipeview-slider img (line 135 in the file).

Matt

On 18 September 2013 11:26, Florenze notifications@github.com wrote:

> I was wondering if you had any tips for making images with different
> resolution look good in swipeview on different devices? or is it not
> possible yet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/309
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by Florenze** [comment]
Thanks it looks really good now.
