### ISSUE TITLE
Can you make a onclick happen on a menuitem (navigator)?

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#310]
I'm having some trouble with the menuitem because i want it to change some sessionScopes when i press the menuitem.  Do you guys have a clever way of  doing this?

**Comment by whitemx** [comment]
Ideally we want to avoid running a server side event in the on click of a menu item element, so my suggestion would be to set the sessionScope variable in the load or render event of whatever page is being loaded when you click the menu item.

If the page being loaded needs some parameters then I would define those via URL parameters in the menu item itself (bearing in mind that our recommendation for the navigator now is to use the computed navigator, you can dynamically build menu items at run time).

Matt
