### ISSUE TITLE
Namespace for all Unplugged clientside JS code 

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#313]
It might be good to namespace all the Unplugged clientside JavaScript code. There are a number of external JavaScript libraries loaded and that might (it doesn't currently) create conflicts in the future.

**Comment by whitemx** [comment]
This is a good idea, something I should have done from the start. My suggestion is that this change forms the entirety of the 3.2 release as it will require a significant amount of retesting work.
