### ISSUE TITLE
Can't edit fields

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#314]
Showing the keyboard on my iPad pushes the footer about halfway up the screen. This causes that I can't edit any field starting from the pushed up footer until the end of the form. Scroll doesn't work anymore too.

Tested with Unplugged 3 on iOS7

![photo 02-10-13 12 21 33](https://f.cloud.github.com/assets/1773707/1252936/3d15cdae-2b58-11e3-837c-773cde4dd8bf.png)

**Comment by markleusink** [comment]
Can't edit all fields of that form on my iPod too. Looks like when the keyboard pops up, it can't scroll anymore. It does depend on what field you set the focus first.

**Comment by markleusink** [comment]
Might be the same issue as this one: https://github.com/teamstudio/Continuity/issues/235

**Comment by whitemx** [comment]
Hi Mark,

I just committed a small code change which hides the footer bar when the keyboard is present. That seems to make things better. Will this work as a solution until we remove iScroll?

Matt

**Comment by markleusink** [comment]
Hi Matt,

I'll have a look at it. This might also be a good solution for the new
release if the controls: gives you some more screen real estate when
filling in forms.

I talked to Steve yesterday on this issue. His suggestion was that I just
wait until the new controls are in their first beta and then update them in
my app.

Regards,
Mark

On Thursday, October 3, 2013, Matt White wrote:

> Hi Mark,
> 
> I just committed a small code change which hides the footer bar when the
> keyboard is present. That seems to make things better. Will this work as a
> solution until we remove iScroll?
> 
> Matt
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/314#issuecomment-25630759
> .

## 

Met vriendelijke groet,
Mark Leusink

---

_Mark Leusink_ (MSc.) | _LinQed BV_ | The Netherlandsm.leusink@linqed.eu |
Cell: +31 (0)6 42 171914 | Skype ID:
mark_leusinkLinkedInhttp://nl.linkedin.com/in/mleusink
 | Blog http://linqed.eu/ | Twitter http://www.twitter.com/markleusink |
Chamber of Commerce reg. 08119980 (KvK Enschede)[image: I'm a two-times IBM
Champion !] https://www.ibm.com/developerworks/lotus/champions/[image:

## IBM Business Partner] http://www.ibm.com/

**Comment by markleusink** [comment]
The fix is only a slight improvement. I've applied it on the 1.7 controls and still am not able to fill in the Employee form: if you set the focus on the first field (Name) I can't scroll anymore so I can only reach all fields by using the left/right keyboard arrows. If I then reach the Start Month field, the footer suddenly is shown again.

Also, if the keyboard is shown, there's a padding between the keyboard and the form. I can only see/ use about 25% of the screen.

![photo 07-10-13 16 54 07](https://f.cloud.github.com/assets/1773707/1281261/70a36800-2f60-11e3-8ad9-b92e75750ad7.png)

**Comment by markleusink** [comment]
Looks like the latest fix did solve some problems with editing forms. But it also introduced a new issue: haven't figured out the details yet, but it looks like iScroll cannot figure out the height of a page anymore, causing that I can't scroll to all content.

**Comment by sives** [comment]
Hmm.  Matt -  sounds like we may need to consider accelerating a release of the new Controls that deletes the iScroll code.

**Comment by whitemx** [comment]
It seems like I have two ways to go then: try and address this iScroll
issue (which I've not really seen yet myself, so will need more detail on)
or remove iScroll altogether from v1.7.1.

If we go for the latter we're looking at about 2-3 days work which will
obviously delay the other 3.0 work which I have going on.

Matt

On 9 October 2013 17:41, sives notifications@github.com wrote:

> Hmm. Matt - sounds like we may to need to consider accelerating a release
> of the new Controls that deletes the iScroll code.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/314#issuecomment-25986894
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by sives** [comment]
Hi Matt,
Let's invest the 2-3 days and remove iScroll altogether from 1.7.1.  It's a lower risk approach, it also has the side benefit of reducing the Javascript processing burden on the mobile device (assuming we don't add a lot more lines of Javascript to implement 1.7.1!).
BR
Steve

**Comment by unplugged** [comment]
Hi Matt,

Let's invest the 2-3 days and remove iScroll altogether from 1.7.1.  It's a lower risk approach, it also has the side benefit of reducing the Javascript processing burden on the mobile device (assuming we don't add a lot more lines of Javascript to implement 1.7.1!).

Can we also make sure we are including the latest JQuery version 2.0.3 in with the 1.7.1 release, since it fixes one important Webkit bug that Unplugged developers might conceivably run up against.

Finally, since this is going to be quite a lot of change from 1.7, can we call it 1.8?

Thanks,
Steve

**Comment by markleusink** [comment]
You said that you didn't really see the issues yourself, so I performed some additional tests using the standard 1.7 controls and the latest unplugged.js fix.

_Standard 1.7 controls (nsf from the OpenNTF download)_
(click on Demo of all widgets and create a new employee or edit one)
- It looks like the form is taller than my viewport, but I can't scroll all the way down.
- If you tap on Name and use the previous/ next links from iOS to browse through the fields (all fields are accessible this way), the footer is moved about 60px up when you enter the Email field.
- When the virtual keyboard is shown, I can’t scroll anymore in the form.
- If the virtual keyboard isn’t shown yet and you tap on a field that will be below the virtual keyboard when it is shown, the footer is moved about 120px up when the keyboard is shown. You can't see or fill in that field and scrolling doesn't work at all.
- I can't scroll in the RT field (if the content of the RT field is longer than the default height).

_Changes to unplugged.js applied (including commit a0002a9836bbe5bead3e93a668062a494f0233ba [a0002a9])_
- All issues remain, except the behaviour of issue 2 is different:
- If you tap on name, the footer is hidden, but there is a blank space about 60px high at the bottom of the page (just above the virtual keyboard). If you tap on Email the height of that blank space gets doubled.
- If you’ve filled in all data (using iOS’ previous/ next button) and the virtual keyboard is hidden again, the title of the form scrolls under the header.
