### ISSUE TITLE
Navigation in demo application isn't logical

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#318]
- A Save of an Employee gets me back to the Homepage: I would expect to go back to the list I came from.
- A Cancel always returns to the Employees list (first menu option in the nav menu): I would expect to go back to the view I came from.

**Comment by markleusink** [comment]
This might be solved with a solution as described in #312

**Comment by whitemx** [comment]
This will be solved in the Unplugged 3.0 Controls.

On 10 October 2013 10:30, Mark Leusink notifications@github.com wrote:

> This might be solved with a solution as described in #312https://github.com/unplugged/unplugged-controls/issues/312
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/318#issuecomment-26039867
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
