### ISSUE TITLE
(cosmetic) Rounded borders in a form in edit mode

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#319]
A form in edit mode has a white background for the rounded borders at the top of the page, the bottom of the form doesn’t show rounded borders at all.

**Comment by whitemx** [comment]
This will be solved in the Controls 3.0 project

On 10 October 2013 10:30, Mark Leusink notifications@github.com wrote:

> A form in edit mode has a white background for the rounded borders at the
> top of the page, the bottom of the form doesn’t show rounded borders at all.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/319
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
