### ISSUE TITLE
(cosmetic) Clear button on a field

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#320]
The clear/ X button in every field shouldn’t be shown if the field has no value. The padding on the right can also be less and the size of that button is relatively large compared to the rest of the page/ the font. There should also be a small white space between the button and the text in the field.

**Comment by whitemx** [comment]
This whole interface is changing in the 3.0 controls

On 10 October 2013 10:31, Mark Leusink notifications@github.com wrote:

> The clear/ X button in every field shouldn’t be shown if the field has no
> value. The padding on the right can also be less and the size of that
> button is relatively large compared to the rest of the page/ the font.
> There should also be a small white space between the button and the text in
> the field.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/320
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
