### ISSUE TITLE
Additional 'button' css required

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#324]
We currently have saveButton, cancelButton and proceedButton - the colors (currently) for proceed and save are the same. For template apps like OneView I need a third button that is a contrasting color (silver is good). Call the class whatever you want (additionalButton etc) but it's required so that when dev's change the css template (and if we update the controls) it automatically changes to any given 'theme'.

**Comment by whitemx** [comment]
I'll forward this on to Jack.

On 16 October 2013 19:43, Rich Sharpe notifications@github.com wrote:

> We currently have saveButton, cancelButton and proceedButton - the colors
> (currently) for proceed and save are the same. For template apps like
> OneView I need a third button that is a contrasting color (silver is good).
> Call the class whatever you want (additionalButton etc) but it's required
> so that when dev's change the css template (and if we update the controls)
> it automatically changes to any given 'theme'.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/324
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by whitemx** [comment]
Hopefully you've got what you need for buttons now with the new UI.
