### ISSUE TITLE
(1.8) Unplugged 'Back' button does not open correct page after attachment opened from AJAX page 

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#325]
I'm not sure if we can do anything about this and it may have to be code added on a per app basis. The URL stored in unp.storedPageRequest only stores the 'AJAX'd' page. After opening an attachment and tapping back the 'popstate' only opens the AJAX content and not the parent XPage, then the AJAX content.

**Comment by sives** [comment]
I thought that Mark Leusink had a solution for this?

**Comment by whitemx** [comment]
What I'm doing in the templates is adding the full UI to the Document
XPages, have a look at
https://github.com/unplugged/documentlibrarytemplate/blob/master/XPages/Document.xspnotice
that the content is wrapped with the layout custom control.

On 18 October 2013 13:52, Rich Sharpe notifications@github.com wrote:

> I'm not sure if we can do anything about this and it may have to be code
> added on a per app basis. The URL stored in unp.storedPageRequest only
> stores the 'AJAX'd' page. After opening an attachment and tapping back the
> 'popstate' only opens the AJAX content and not the parent XPage, then the
> AJAX content.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/325
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by sives** [comment]
I get a 404 error when I click on this URL

**Comment by RichSharpe** [comment]
Knock of the 'notice' at the end of the URL.

So (Matt) are you saying we _must_ use a layout control now for this to work :-(
I've managed to solve this issue in another custom app - it's a little different but I'll test if it works. The downside is that the pushstate URL will need to be manually edited for each app :-( and then a beforePageLoad check to ensure the parent loads the AJAX'd content again via a UNID param.

Richard Sharpe
Technical Director
richard_sharpe@teamstudio.com
+1 480-307-0528

http://unplugged.teamstudio.com

**Comment by whitemx** [comment]
Yes any page which can open an attachment must be edited in this way. It
took me only an hour to do all three sample apps though, so not a massive
change.

On 18 October 2013 14:44, Rich Sharpe notifications@github.com wrote:

> Knock of the 'notice' at the end of the URL.
> 
> So (Matt) are you saying we _must_ use a layout control now for this to
> work :-(
> I've managed to solve this issue in another custom app - it's a little
> different but I'll test if it works. The downside is that the pushstate URL
> will need to be manually edited for each app :-( and then a beforePageLoad
> check to ensure the parent loads the AJAX'd content again via a UNID param.
> 
> Richard Sharpe
> Technical Director
> richard_sharpe@teamstudio.com
> +1 480-307-0528
> 
> http://unplugged.teamstudio.com
> 
> On Oct 18, 2013, at 9:05 AM, sives notifications@github.com wrote:
> 
> > I get a 404 error when I click on this URL
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/325#issuecomment-26596421
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB

**Comment by markleusink** [comment]
Here's how I think this should be implemented:
- All Ajax loads are handled by a few functions in unplugged.js (loadPage(), openDocument() ).
- Those function should add a URL parameter to every call indicating that it's an Ajax load (e.g. &ajaxLoad=true).
- The URL that is stored (in the same functions) in the history object should be the original URL (without the Ajax load parameter). That way, if a user hits back (after opening an attachment), the URL without the ajaxLoad parameter is loaded.
- Using the **ajaxLoad** URL parameter you can then set the **rendered** property of everything that doesn't need to be included for Ajax calls (header, footer, menu, resources).
