### ISSUE TITLE
Hide for edit-button

### ISSUE THREAD

**Issue by ThorstenWGZ** [unplugged/unplugged-controls#326]
The panel around the edit-button is missing the computed hide-when: compositedata.editxpagename

**Comment by whitemx** [comment]
We currently allow you to choose whether to display the Edit and Close buttons on the FormViewer control on the assumption that if you can see the document, then you can edit it. 

If you want to apply business logic to this decision then you can simply hide the default buttons and add your own inside the FormViewer tags.
