### ISSUE TITLE
Adding ACL elements 

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#329]
We are running the attached script to setup our ACL fields on all the documents we create, we are getting no errors or any of the fields set on our documents. To save we are using a Simple Action Save Document.

The script is in a querySaveDocument, and as far as we can read all of the things we are trying to do is supported by unplugged. Is unplugged not able to set ACL fields on a document, or is there something else wrong?

var setNameField = function(dataSource, namesList, delim, dataSourceFieldName, flagType) {
 if (namesList.indexOf(delim)!=-1) {
  var tempArray = namesList.split(delim);
  var nameArray = new Array();
  for (k in tempArray)
    if(tempArray[k]) nameArray.push(fullTrim(tempArray[k]));
 } else {
  nameArray = namesList
 }
 var doc = dataSource.getDocument(true);
 var item = doc.replaceItemValue(dataSourceFieldName,nameArray);
 switch (flagType) {
  case 'NAMES' :
   item.setNames(true);
   break;
  case 'AUTHORS' :
   item.setAuthors(true);
   break;
  case 'READERS' :
   item.setReaders(true);
   break;
  default : 
 }
 if(nameArray.length==0 && dataSource.hasItem(dataSourceFieldName)) {
  dataSource.removeItem(dataSourceFieldName)
 } else {
  dataSource.replaceItemValue(dataSourceFieldName, item)
 }
  //dataSource.save();
}

**Comment by RichSharpe** [comment]
So Unplugged does not support setting Author/Readers fields on device (for technical reasons and this _may_ change in the future). The way to do this is to create an Agent on the server that performs this task when a specific (hidden??) field on a doc is modified and the agent is set to 'run on new or modified doc' and a test for this new flag is in the agent.

**Comment by RichSharpe** [comment]
One more thing on this.... If you need the agent to run straight away give it an alias of TMSRunAfterPush This will force Unplugged to push this request to the front of the Agent Manager queue and it will run 'next'
