### ISSUE TITLE
unpDebugToolbar problems

### ISSUE THREAD

**Issue by weal-zz** [unplugged/unplugged-controls#330]
Hi

if I try to use the DebugToolbar in my database (which is used via unplugged and web access), I get the following error:

![image](https://f.cloud.github.com/assets/4990827/1436279/4d4a21be-4153-11e3-87ed-7a31ef3a70a9.png)

All works fine with Unplugged, but not if I open the database directly via browser.
(same behavior with the demo in unplugged controls library)

I wasn't able to figure out why this is happening or how it can be fixed.

**Comment by whitemx** [comment]
In the current release, the Debug Toolbar doesn’t work for a web browser, it is supported for the Unplugged client only.

In the upcoming release this issue has been resolved.
