### ISSUE TITLE
unpWorkspace control has Continuity artifacts included

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#331]
I think these 'alert levels' and such need to be moved from the CC. They can be put in the XPage for the demo to show something but they get displayed if I create my own workspace.

**Comment by whitemx** [comment]
If you leave the properties blank then the alert levels area shouldn’t show. I’ll investigate.

Are you working against 1.8 or 3.0?

Matt White 
Fynn Consulting Ltd
Office: +44 7767 384970 
Email: matthew.white@fclonline.com
Twitter: @mattwhite
Website: http://fclonline.com 

Fynn Consulting Ltd is a limited company registered in England and Wales.Company Registration No. 4954250
Registered Office: 24 Ivymount Road, London, SE27 0NB
