### ISSUE TITLE
Teamroom template issue in Edit mode

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#333]
There seems to be a problem with the Teamroom template - maybe it's an issue with the Unplugged Controls. If you edit a document and change the category field, especially if you change from one item selected to multiple items selected (or vice versa), the changes aren't stored correctly. This also applies to the teams and subteams fields, which is why I think it's an issue with the controls.

**Comment by whitemx** [comment]
Hi Steve

I'm testing on my dev databases and all seems to be working OK, what is the
issue that you're seeing?

Matt

On 12 November 2013 12:52, sives notifications@github.com wrote:

> There seems to be a problem with the Teamroom template - maybe it's an
> issue with the Unplugged Controls. If you edit a document and change the
> category field, especially if you change from one item selected to multiple
> items selected (or vice versa), the changes aren't stored correctly. This
> also applies to the teams and subteams fields, which is why I think it's an
> issue with the controls.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/333
> .

## 

_Matt White_
Phone - +44 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 24 Ivymount Road, London, SE27 0NB
