### ISSUE TITLE
Mobile Toggle Switch

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#335]
Martin Perrie asked (via Twitter) for a new toggle control (or at least some support for one in the Form Editor control).

**Comment by whitemx** [comment]
I think this will need some UI love from Jack.

**Comment by jackherbert** [comment]
Sure, how should we approach this?

**Comment by sives** [comment]
Is it clear exactly what is needed here?  I looked at Martin's tweet and it was pretty short.  Matt - perhaps you could first get a longer summary of what Martin is looking for.  Or is it just a Yes/No type of toggle?

**Comment by whitemx** [comment]
I was imagining that we need to do something like this:
![screenshot 2014-01-13 21 15 12](https://f.cloud.github.com/assets/856638/1904987/db22307e-7c97-11e3-8296-a4baf1e621c6.png)

Though obviously designed to work across iOS and Android and maybe allow us to insert our own labels in place of On and Off?

**Comment by sives** [comment]
Yes, it would be great to have this in the Form editor control.  Maybe Jack can provide some HTML + CSS

**Comment by jackherbert** [comment]
I'm not sure what's best for markup (in terms of working with Unplugged)

Matt - do you want to put together some basic markup that works, then I can style it up, or should I come up with some markup myself and you can make it work afterwards?

**Comment by whitemx** [comment]
Hi Jack

I think in this case if you can suggest the markup I should be able to work with it.

Matt

**Comment by jackherbert** [comment]
Cool, I've had a look around, and hopefully we can achieve it with reasonably simple, semantic markup:

```
<div class="switch">
    <input type="checkbox" id="switch"/>
    <label for="switch">YES</label>
    <label for="switch">NO</label>
</div>
```

If you could add that in a row to one of the Sampler App forms on the dev version – in place of an input and in some sort of realistic context (perhaps with a label like "Admin" or "Private" – I'll get it looking/behaving right with CSS

**Comment by whitemx** [comment]
OK so I've added a new field to the Forms Edit page. The markup has to be slightly different to what you asked for, based on what the server generates, hopefully you'll be able to work with it:

http://isightcss.londc.com/CSSSampler.nsf/FormsEditMode.xsp

```
<li>
  <label for="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" class="xspTextLabel">Mobile Enabled</label>
  <div class="switch">
    <label for="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" class="xspCheckBox">
      <input id="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" type="checkbox" name="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" class="xspCheckBox" onchangetrigger="early-onclick">Label
    </label>
    <label for="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" class="xspTextLabel">YES</label>
    <label for="view:_id1:_id2:callback1:_id41:_id42:callback1:mobileenabled" class="xspTextLabel">NO</label>  
  </div>
</li>
```

One thing to also note is that I've made a change to the CSS / LESS files (for radio button styling) so make sure to use the files in the application.

Shout if I can change anything to make it work better.

**Comment by jackherbert** [comment]
Thanks Matt. I've had a look, but I don't think I can make it work because the <labels> aren't siblings of the <input>, so we can't update their styles when it's checked (not without JS anyway. Could the markup be tweaked?

**Comment by whitemx** [comment]
Sorry for the delay in replying, was travelling last week.

Unfortunately I can only do the markup in one of two ways, the way you've already seen or as a second example the server can generate table markup. If we need to write JavaScript then I guess that's what we'll do.

I've added the table markup as an example.
