### ISSUE TITLE
Styling of radio buttons

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#337]
The default styling for a radio button group picks up styles from the formeditor labels and needs to be overridden. Not sure how you'd want them to look by default to fit in with other elements on a form, but what about something like this ?http://viralpatel.net/blogs/css-radio-button-checkbox-background/

**Comment by sives** [comment]
Agreed.  I also agree with Martin's styling suggestion.

**Comment by whitemx** [comment]
I suspect this should be left open, I'll add it to the list for 3.1.

**Comment by whitemx** [comment]
This has been fixed in the latest build.
