### ISSUE TITLE
FontAwesome icons do not display when using [mobile] web browser

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#342]
Console give a 404 error (Failed to load resource) and is expecting (looks like) the files font awesome-webfont.\* to be in the root??

**Comment by whitemx** [comment]
Have you got an example of this I can test? It's working on the sampler at http://unp.londc.com/UnpSampler.nsf/UnpMain.xsp

**Comment by RichSharpe** [comment]
Try this one - it's a simple DB with just a header and footer

**Comment by whitemx** [comment]
Sorry, no file attached, could you email it to me and I'll have a look.

**Comment by whitemx** [comment]
Solution to this was to turn off consolidated JS / CSS in the XPages properties
