### ISSUE TITLE
UnpComputedNavigator - subMenus of last nav entry do not display correctly

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#343]
If the last entry in a UnpComputedNavigator has sub-entries then the sub-entries all have rounded bottom corners (borders) as if they were the last entry in the list.

**Comment by RichSharpe** [comment]
I believe the sub-menu li's are inheriting the last-child attribute. A similar issue occurs if the sub-menus are included in the first menu-item, albeit the tops of the borders of the subs are rounded. Again, they are inheriting the first-child attribute in this case.

**Comment by jackherbert** [comment]
Thanks Rich, I've uploaded a CSS fix for this to isightcss
