### ISSUE TITLE
Syncing from a page loaded via ajax will load the ajax'd content only 

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#345]
When openDocument(string, string) is called the url is pushed onto the history stack. If a page is opened this way and the sync button is in the footer, hitting sync will replicate and Unplugged will attempt to open the xpage on the top of the url history stack.
I'm not sure if a custom property in the footer is needed to define which page should be opened post-sync? (will require a change in Unplugged) or if there is another way to store the url history so this does not occur.
There are use cases where ajax'd documents will allow the user to sync.

**Comment by RichSharpe** [comment]
Actually if a custom property can be added to the footer ('PostSyncTarget'??), the onCLick event on the Sync button could push this url/xpage to the history stack before calling 'replicate' - then there will be no need for a change in Unplugged.

**Comment by whitemx** [comment]
I've added a new custom property to the UnpFooter and UnpTabbedFooter "postSyncTarget" this URL will be opened after performing a Sync. If the property is not set then the exist then the existing functionality will continue.
