### ISSUE TITLE
Add Camera Support

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#346]
"It would be great if the Mobile Controls included the facility, out of the box, to interact with the camera and carry out a non-Ajax save to upload pictures. Currently (at least in v1.8) I think it only handles an Ajax save so I've had to add extra code in from the camera demo app to handle this (and spend the time getting to the bottom of this issue too!).”

Raised by Martin Perrie

**Comment by RichSharpe** [comment]
This video shows how to do this (it uses 1.8 controls but is still valid):
https://www.youtube.com/watch?v=dITMq2eDzcE
It is non-ajax.

**Comment by RichSharpe** [comment]
Martin's issue was with fastclick not the camera integration.
