### ISSUE TITLE
UnpFlatView does not honor the dbName if external

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#349]
Looks like line 93 of the UnpFlatView control uses getDbPath() to set the URL for the target doc (onclick) where this should be the db var on line 24 if in a different DB.
Currently I get a 404 error as the URL is:

http://currentDb/DbIReallyWant/doc

**Comment by whitemx** [comment]
I suspect what we want here is a second DbPath custom property, you may want to get the data for the view from another database, but the XPage which shows the document is most likely to want to reside in the current database.

**Comment by RichSharpe** [comment]
D'oh! Of course. This was a hangover from Unplugged not supporting external DS for documents. Even though that functionality is now supported there are use cases where the data from the view and document details need to come from an external DB.

**Comment by whitemx** [comment]
So I'm in the process of adding "xpageDocDBName" as a new property which will get used for building the URL to the XPage when opening a document.
