### ISSUE TITLE
Using Dojo in unplugged

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#350]
We are having trouble using dojo in unplugged we assumed it would be implicit, but it does not work and none of your controls reference it, so the way you want us to use it is by adding it explicit where we need it?

**Comment by whitemx** [comment]
At the moment Dojo is included in the Unplugged application, but this is going to change in a future release, so our advice would be to use jQuery if you can. If you do need to use Dojo then, yes you'll need to include the JS files inside your application to get them inside Unplugged.
