### ISSUE TITLE
FormEditor not working?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#351]
I have been having trouble getting the formEditor control to work. The problem i am having is that it wont let me create documents in another database. Instead it just creates documents in the database that i am in.

This is my code:

<?xml version="1.0" encoding="UTF-8"?>
<xp:view xmlns:xp="http://www.ibm.com/xsp/core"
    xmlns:unp="http://unplugged.teamstudio.com">

```
<xp:this.data>
    <xp:dominoDocument var="document1"
        databaseName="Unplugged/spp_vi11.nsf" formName = "formVisit" 
        action="editDocument">

    </xp:dominoDocument>
    </xp:this.data>

    <xp:this.resources>

    <xp:styleSheet href="/unplugged.css"></xp:styleSheet>
    <xp:script src="/unplugged.js" clientSide="true"></xp:script>

</xp:this.resources>

<unp:unpHeader search="none" searchPage="UnpSearch.xsp"
    viewsButton="false">
</unp:unpHeader>






<div id="contentwrapper">
<unp:unpScrollableArea>
<xp:this.facets>
<unp:unpFormEditor showbuttons="yes" viewxpagename="unpMain.xsp"
    formname="formVisit" title="Edit Besøg" xp:key="facet_1"
    dbName="Unplugged/spp_vi11.nsf" position="menu-aligned">
    <xp:this.facets>
        <xp:panel xp:key="facet_1">
            <ul class="fieldlist">

                <li>
                    <xp:label value="Besøgs Type" id="label1"
                        for="subject">
                    </xp:label>
                    <xp:inputText id="cSalesGroup_fi"
                        value="#{document1.cSalesGroup_fi}">
                    </xp:inputText>
                </li>

            </ul>
        </xp:panel>
    </xp:this.facets>



</unp:unpFormEditor>
</xp:this.facets>
</unp:unpScrollableArea>
```

</div>
    <unp:unpFooter newDocLoadType="full" synctype="alldbs">/unp:unpFooter/xp:view

I just have a single field for testing.

As you can see I've set the formEditor dbName to be "Unplugged/spp_vi11.nsf". However it just creates blank document in my current database that have fields like "formname" that are set to "formVisit". So it seems that it is taking the parameters of the formEditor and using them as fields in documents that it is creating. It is really very confusing.

I'm sure that i've done something wrong, hope you can help.

**Comment by whitemx** [comment]
Hi John,

In the 3.0 controls we don't support editing data in another database, but we have literally just added this functionality in development for the 3.1 release which we are targeting for early February. You can see the changes in Github, mainly in this commit: https://github.com/unplugged/unplugged-controls/commit/a94c0511f11dc86c51ab2495f0473338c83ac196

Hope that helps.

Matt
