### ISSUE TITLE
getting the value of a Combobox

### ISSUE THREAD

**Issue by Florenze** [unplugged/unplugged-controls#352]
I have a problem with Comboboxes and their values

getComponent(combobox).getValue()  is null.

So i tried using jQuery the way that unplugged uses it and i made it do a thing with 
    return "$.blockUI();window.location.href='" + "unpMain.xsp" + "';";
And that worked. Then i tried:

return "$.blockUI(); var out = $('Combobox').val();window.location.href='unpMain.xsp'+out;";

and alot of variations of that but no luck. 

Can you help me team unplugged?

all of this is on a onchange combobox attribute

**Comment by RichSharpe** [comment]
Hi Florenze. I'm going to move this question over to https://getsatisfaction.com/teamstudio/products/teamstudio_inc_teamstudio_unplugged
This GH project is only for the Unplugged Controls, not the Unplugged product. If you have question outside of the actual controls I would recommend you list them at the above forum. The forum is the official 'Unplugged' support forum.
