### ISSUE TITLE
Accordion with category filtering?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#353]
Hey,

I am wondering what the easiest way for me to add the category filtering functionality from the Flat View (the "categoryfilter" and "categoryindex" properties) into the Accordion View is? The reason for this is because I would like to have both the Accordion's categorized view, as well as be able to filter which documents to view as I can in the Flat View.

I am not sure what the easiest way to do this is, or if it's feasible at all? If you have any tips or suggestions I would really like to hear them.

**Comment by whitemx** [comment]
This is not something we current support, I have a suspicion that we may run into view design issues, but it's definitely something we'll investigate for a future release.

**Comment by whitemx** [comment]
I have this working in dev for 3.2, but have come across an issue which affects iOS, so will need to put this on hold until the dev team have had a chance to look into it.
