### ISSUE TITLE
Creating documents in different database?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#354]
Hey,

I was previously trying to edit documents in a different database, which you said was no yet possible, is this also the case for creating documents? I am simply trying to create a basic document using the FormEditor, but it keeps creating documents in my current database. This is the code I use:

xp:this.data
        <xp:dominoDocument var="document1"
             formName = "formVisit">
unp:this.databaseName<![CDATA[#{javascript:var lastslash = database.getFilePath().lastIndexOf("/");
var dbname = "/"+database.getFilePath().substr(0,lastslash)+"/spp_vi11.nsf";

return dbname;}]]>/unp:this.databaseName
        /xp:dominoDocument
        /xp:this.data

```
    <xp:this.resources>

    <xp:styleSheet href="/unplugged.css"></xp:styleSheet>
    <xp:script src="/unplugged.js" clientSide="true"></xp:script>

</xp:this.resources>

<unp:unpHeader search="none" searchPage="UnpSearch.xsp"
    viewsButton="false">
</unp:unpHeader>






<div id="contentwrapper">
<unp:unpScrollableArea>
<xp:this.facets>
<unp:unpFormEditor showbuttons="yes" viewxpagename="unpMain.xsp"
    formname="formVisit" title="Edit Besøg" xp:key="facet_1" position="menu-aligned"

    >
    <unp:this.dbName><![CDATA[#{javascript:var lastslash = database.getFilePath().lastIndexOf("/");
```

var dbname = "/"+database.getFilePath().substr(0,lastslash)+"/spp_vi11.nsf";

return dbname;}]]>/unp:this.dbName
        xp:this.facets
            <xp:panel xp:key="facet_1">
                <ul class="fieldlist">

```
                <li>
                    <xp:label value="Besøgs Type" id="label1"
                        for="subject">
                    </xp:label>
                    <xp:inputText id="cSalesGroup_fi"
                        value="#{document1.cSalesGroup_fi}">
                    </xp:inputText>
                </li>

            </ul>
        </xp:panel>
    </xp:this.facets>



</unp:unpFormEditor>
```

I use javascript to get the database name here, but i have also tried simply typing it in as a string directly, none of it seems to have any effect at all.
I remember being able to previously create documents in another database, so I am wondering why exactly this is happening. I could understand if the document was not created in the other database as many things could cause that, but I don't understand why it creates one in my current database (I have no forms or views in this database, it just creates blank documents with that single field). It just ignores the dbName property completely. 

Is this simply a case of this feature not yet having been implemented, or do you have any idea as to what I am doing wrong?

Thank you.

**Comment by whitemx** [comment]
Hi John,

The controls have supported viewing data from other databases for some time, but never saving it (or creating new document). The dbName property was partially implemented at a stage when we thought we could get it working, but then found we couldn't. 

AS of the upcoming 3.1 release (due in Febuary) we will finally be able to add the change that supports full creation and editing of data in other databases.

At the moment, even if the dbName is specified the data will be inserted into the current database, the code which does this is in the UnpSaveDocument XPage, so if you want to get a jump on 3.1 I would recommend looking at the latest version of the code here to see how we are working with the dbName property. You will require changes in the UnpFormEditor, unplugged.js and UnpSaveDocument design elements.

Matt
