### ISSUE TITLE
Removing closeXPageName from unpFormViewer causes an issue

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#357]
If you have a unpViewList in UnpMain and then click through to an xpage with a unpFormViewer and then click to edit - taken to an xpage with unpFormEditor, tap cancel and you are correctly taken back to the unpFormViewer xpage, click Close and you are taken to the xpage with the unpFormEditor, not the UnpMain.xsp.
I think it is more flexible allowing hte dev to control where the navigation executes so I'd recommend putting the closexpagename back in.

**Comment by whitemx** [comment]
I've not fixed this so will reinvestigate

**Comment by whitemx** [comment]
Ah so the issue here was documentation. Basically the structure of the XPages needs to be like this:

``` XML
<div id="content">
   <div id="contentwrapper">
    <unp:unpScrollableArea>
      <xp:this.facets>
        <unp:unpFlatView insetData="true" numberofrows="20"
          refreshmethod="pull" position="menu-aligned" xp:key="facet_1"
          viewName="(UnpAllDocuments)" xpageDoc="UnpDocument.xsp" title="All Documents"
          summaryColumn="Topic" detailColumn="Modified">
        </unp:unpFlatView>
      </xp:this.facets>
    </unp:unpScrollableArea>
   </div>
  </div>
```

The key being the contentwrapper being inside content. I've updated the documentation accordingly
