### ISSUE TITLE
UPMark does not run

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#360]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app in portrait mode and go to UPMark
2. Click on Start test

Expected result:
3. Test is run successfully

Actual result:
3. Nothing happens

**Comment by whitemx** [comment]
I only have a Nexus 7 on the Android tablet side of things, but it's working correctly for me.
