### ISSUE TITLE
Load more from media library does not work

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#361]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app in portrait mode and go to media library
2. Click on load more button

Expected result:
3. More documents gets loaded

Actual result:
3. Only load more button gets displayed
4. When changing the rotation to landscape view, more documents get displayed
![screenshot_2014-02-16-23-00-30](https://f.cloud.github.com/assets/2638956/2182482/8d0ece8c-978c-11e3-90bc-b4c593f9a58c.png)
![screenshot_2014-02-16-23-03-19](https://f.cloud.github.com/assets/2638956/2182483/8d26ecba-978c-11e3-8547-4010e058069b.png)

**Comment by whitemx** [comment]
I only have a Nexus 7 to test this on, but it's working OK for me.

**Comment by whitemx** [comment]
Tested in Nexus 10 and this seems to work now. Not sure what I did to fix it though!
