### ISSUE TITLE
Images not displayed in swipe view when in landscape mode

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#362]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open app in portrait mode and go to swipe view
2. Observe that images get displayed and swiping works
3. Change orientation to landscape mode

Expected result:
4. Images displayed

Actual result:
4. No images get displayed
![screenshot_2014-02-16-22-38-44](https://f.cloud.github.com/assets/2638956/2182489/a24fac4e-978c-11e3-9f16-74498ef1b815.png)

**Comment by whitemx** [comment]
Again working correctly on Nexus 7.

**Comment by whitemx** [comment]
Resolved on Nexus 10.
