### ISSUE TITLE
Flat view doesn't display documents cross the screen in landscape view

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#363]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app and select flat view

Expected result:
2. All the documents get rendered cross the screen

Actual result:
2. Documents stay right aligned and don't change the width
![screenshot_2014-02-16-22-28-34](https://f.cloud.github.com/assets/2638956/2182494/c89cf046-978c-11e3-894e-a56a98ef8eee.png)
![screenshot_2014-02-16-22-28-52](https://f.cloud.github.com/assets/2638956/2182495/c89eb2dc-978c-11e3-9caf-01c3caec4662.png)

**Comment by whitemx** [comment]
This appears to be more of an issue with the navigator menu , in Landscape mode on a large tablet, the menu should automatically display. This is one for Jack to look at.

**Comment by jackherbert** [comment]
In Android (and Android only it seems), there's an inline "position:relative" on #menuitems which may be causing the problem. Any idea where this is coming from or what it's for?

**Comment by RichSharpe** [comment]
This is definitely the UnpNav css. This works fine in the Unplugged SWT but I can recreate using Samsung Galaxy 10.1. It looks like Android 'weighs' the CSS differently. Line 654 of unplugged.css (and the unplugged-dark.css etc) has #menuitems .menulink with position:relative. 
If I add position:fixed !important to line 599 (@media screen and (min-width:1001px;)) Then the nav shows but the contents are not the correct size. Maybe we need a @media screen and (min-width:1001px;) for all attributes specific to the UnpNav.

**Comment by whitemx** [comment]
This should be resolved now. (Tested in Nexus10 which exhibited the same bug)

**Comment by AdyMakombo** [comment]
I am running into the same problem on an iPad running iOS 7.1.1 and Unplugged 3.1.1 (22686).

**Comment by whitemx** [comment]
Hi Ady. We'll need some details as i use the control on the ipad all the time and haven't ever seen this issue.

Thanks

Matt

**Comment by AdyMakombo** [comment]
Here is the code I am running. 1) I copied the UnpDemoWidgets xPage, 2) removed the navigator 3) specified position="left-aligned" and 4) I customized the Header and footer to remove the Search field and the New button...

<?xml version="1.0" encoding="UTF-8"?>

<xp:view xmlns:xp="http://www.ibm.com/xsp/core" xmlns:xc="http://www.ibm.com/xsp/custom"
    xmlns:unp="http://unplugged.teamstudio.com">

```
<xp:this.resources>
    <xp:styleSheet href="/unplugged.css"></xp:styleSheet>
</xp:this.resources>

<unp:unpHeader search="none" viewsButton="true"
    headerHomeLink="/unpws.unp" title="Nalcor Time Sheet">
</unp:unpHeader>

<div id="content">
    <div id="contentwrapper">
        <unp:unpScrollableArea>
            <xp:this.facets>
                <unp:unpFlatView insetData="true" detailColumn="DOB"
                    summaryColumn="Name" title="By Employee" viewName="Employees"
                    xpageDoc="Employee.xsp" xp:key="facet_1" numberofrows="20"
                    refreshmethod="pull" position="left-aligned" photoColumn="Photo"
                    wrapsummarytext="yes">
                </unp:unpFlatView>
            </xp:this.facets>
        </unp:unpScrollableArea>
    </div>
</div>

<unp:unpFooter synctype="currentdb"
    postSyncTarget="/UnpMain.xsp">
</unp:unpFooter>
```

/xp:view

**Comment by whitemx** [comment]
And if you remove the left-aligned property?

**Comment by AdyMakombo** [comment]
Removing the left-aligned property does not change anything. In fact, when I remove that property, the problem occurs even in a browser such as Chrome. With the left-aligned property, Chrome looks ok.

**Comment by whitemx** [comment]
OK I have tracked down the issue. you will need to modify line 1068 of unplugged.css to:

```
@media screen and (min-width: 1001px) {
  .pullleft,
  .left-aligned {
    margin-left: -42.8% !important;
  }
  .accpullleft {
    margin-left: -42.8% !important;
  }
}
```

**Comment by AdyMakombo** [comment]
The recommended fix worked for the main page (UnpMain.xsp) but not for the page (i.e: Employee.xsp) opened off of the main page. I added the lines below to make it work:

@media screen and (min-width: 1020px) {
    #formholder {
      margin-left: -42.8%;
    }
}
