### ISSUE TITLE
Accordion view doesn't remember previous selection

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#364]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app and select accordion from UI elements
2. Open the last category
3. Select a document to view
4. Close the document

Expected result:
5. Accordion still shows the last category opened

Actual result:
5. First category gets opened when going back to the category view

**Comment by KristelViidik** [comment]
Same with flat view. Going back to the view gets you to the beginning of the list.

**Comment by whitemx** [comment]
This is a know issue #332 which we still haven't worked out a good solution to.
