### ISSUE TITLE
How is the alignment supposed to work?

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#365]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app in portrait mode
2. Click on UI elements CSS controls
3. Observe that all the panel controls are rendered cross the screen
4. Rotate the view to landscape

Expected result:
5. All the panels get rendered cross the screen and the buttons would be left aligned

Actual result:
5. Observe that only the left aligned panel gets rendered cross the screen. Buttons get anchored somewhere in the middle of the screen. Is this expected behaviour?
![screenshot_2014-02-16-22-17-56](https://f.cloud.github.com/assets/2638956/2182500/09d9f8ec-978d-11e3-90d8-3c9059899db5.png)

**Comment by whitemx** [comment]
This is correct. We have two versions of "left aligned". On a large tablet most elements should be indented from the left hand side to allow the navigator menu to display.
