### ISSUE TITLE
Accordion - clicking on the category doesn't mostly work

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#367]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open app and select accordion from the UI elements
2. Click on the category

Expected result:
3. Category gets expanded when clicking

Actual result:
3. Mostly nothing happens. Note that it's mainly the problem with UK category. It very rarely gets expanded while other categories usually do (but not always).
![screenshot_2014-02-16-22-06-59](https://f.cloud.github.com/assets/2638956/2182509/4a7f69a4-978d-11e3-8340-6cff85c8634e.png)

**Comment by whitemx** [comment]
Tested on Nexus 7 this works correctly.

**Comment by whitemx** [comment]
In fixing one of the other bugs, there was an issue where there was an invisible column about 100px wide on the left hand side of the screen which prevented clicking in that area for portrait Android tablet devices. I suspect that may have been the issue.
