### ISSUE TITLE
Charts displayed double on dashboard

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#368]
Environment:
Sony Xperia Z tablet Android 4.3

Steps to reproduce:
1. Open the app and go to dashboard
2. Observe that all the charts are displayed correctly (even though they are aligned right of the screen leaving empty space on the left)
3. Click on the style buttons on the bottom

Expected result:
4. All charts displayed correctly

Actual result:
4. Observe that the charts are displayed double (see screenshot)
Note that also rotating doubles the charts.

![Uploading Screenshot_2014-02-16-21-26-03.png . . .]()
![Uploading Screenshot_2014-02-16-22-03-29.png . . .]()

**Comment by whitemx** [comment]
Tested on Nexus 7 this works OK.

**Comment by whitemx** [comment]
Unable to reproduce this on a Nexus 10 as well.
