### ISSUE TITLE
Contact editing shows html in Details section

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#369]
Steps to reproduce:
1. Open Contacts > Contacts from Views menu.
2. Click on Sofia Acey.
3. Click Edit.

Expected result:
If details is empty it should be empty in edit view.

Actual result:
I'm seeing html element p instead.
![img_0293](https://f.cloud.github.com/assets/2638956/2182518/8eec3248-978d-11e3-9ce7-814f97d44769.PNG)

**Comment by whitemx** [comment]
Resolved this issue, it was a test data problem rather than a bug with code.
