### ISSUE TITLE
Standard CSS not included automatically 

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#37]
Dragging in controls from a new XPage does not render the contents correctly unplugged.css must be added to the XPages as an explicit resource. Should we have a 'mandatory scripts' control? Or should this be documented?

**Comment by whitemx** [comment]
This is already documented here:
https://github.com/unplugged/unplugged-controls/wiki

On 10 December 2012 16:02, RichSharpe notifications@github.com wrote:

> Dragging in controls from a new XPage does not render the contents
> correctly unplugged.css must be added to the XPages as an explicit
> resource. Should we have a 'mandatory scripts' control? Or should this be
> documented?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/37.

## 

_Matt White_
Phone - +44 (0) 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 45 Tivoli Road, London, SE27 0ED

**Comment by RichSharpe** [comment]
OK - do you think this is enough or should we add it to the Design Def in the CC also?

**Comment by whitemx** [comment]
I'll do that now :-)

On 10 December 2012 16:11, RichSharpe notifications@github.com wrote:

> OK - do you think this is enough or should we add it to the Design Def in
> the CC also?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/37#issuecomment-11202705.

## 

_Matt White_
Phone - +44 (0) 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 45 Tivoli Road, London, SE27 0ED
