### ISSUE TITLE
Text Editing Panel with keyboard hides save and cancel buttons

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#370]
Steps to reproduce:
1. Open Typography > Text Editing Panel
2. Click on the text to start changing text.

Expected result:
After changing text I want to see save or cancel buttons to finish editing.

Actual result:
Can't see the buttons, but I did know they are probably there so I scrolled them into view by dragging from outside of textarea itself. Not intuitive if it's meant to be like that.
![img_0291](https://f.cloud.github.com/assets/2638956/2182526/e09d7034-978d-11e3-84d2-800a8e872122.PNG)
![img_0292](https://f.cloud.github.com/assets/2638956/2182527/e0a21846-978d-11e3-8447-770bbc0f53de.PNG)

**Comment by whitemx** [comment]
Not sure what we can do to improve this, something for Jack to weigh in on?

**Comment by jackherbert** [comment]
This is something I've noticed on other apps too, and it is annoying (I normally hide the keyboard, then choose an action, but it doesn't seem 100% fluid)

We could put the Save/Cancel buttons at the top of the panel, above the textarea?

**Comment by markokruustuk** [comment]
It would help I think as in the bottom it's not visible at all. Although the top bar is half hidden as well as you can see from the screenshot, but as long as you can at least see half of the buttons you know what to do.

**Comment by whitemx** [comment]
I'll make sure this gets added to the list of items to discuss for the 3.2 dev cycle as it's a change rather than a bug.

**Comment by whitemx** [comment]
After discussion with Steve / Rich we're going to revert this due to future plans.
