### ISSUE TITLE
Text Reading Panel zoom out until you can't see text and zoom in again will show all texts in same size

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#371]
Steps to reproduce:
1. Open Typography > Text reading panel
2. Zoom out until you can't see the text
3. Zoom in again until all the text is visible and in normal size

Expected result:
I expect to see different font sizes after zooming in again.

Actual result:
All font sizes are the same.
![img_0290](https://f.cloud.github.com/assets/2638956/2182530/fd02df48-978d-11e3-9e2b-b90c694ca0b1.PNG)

**Comment by KristelViidik** [comment]
Same on Sony Xperia Z tablet Android 4.3

**Comment by whitemx** [comment]
One for 3.2 as it's not a critical bug.
