### ISSUE TITLE
Form (Edit Mode) doesn't allow proper scrolling

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#372]
Steps to reproduce:
1. Open UI Elements > Form (Edit Mode).
2. Click on a text field to bring up the keyboard.
3. Scroll up and down by dragging with a finger.

Expected result:
I expect the scrolling to work smoothly and take me top or down in one go.

Actual result:
Scrolling stops in the middle and I have to scroll again to get to top or bottom. See attached video.

**Comment by whitemx** [comment]
Not sure there's much we can do about this. Will investigate in 3.2

**Comment by whitemx** [comment]
Not a huge amount I can do to improve this unfortunately.
