### ISSUE TITLE
Dialog opens under menu in landscape mode where you can't hide the menu

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#374]
Steps to reproduce:
1. Open Dialog from UI Elements from Views menu on the left.
2. While in Landscape mode, click on Open Dialog.

Expected result:
I expect to fully see the dialog.

Actual result:
Menu covers a part of the dialog so I'm not able to read the content.
![img_0287](https://f.cloud.github.com/assets/2638956/2182543/b240bc04-978e-11e3-9fab-3df5f2aded61.PNG)

**Comment by jackherbert** [comment]
I've added a z-index:999 on the surrounding div (.iscrollcontent), which should make sure the dialog & overlay display above the menu.

**Comment by jackherbert** [comment]
Actually, that's no good because now the content area _always_ appears above the menu.

Can we get a special classname on this div (or on the body) when a modal is active? Then I can turn on the z-index when we need it

**Comment by whitemx** [comment]
I've added a new class to the dialog div called "dialogactive", is that sufficient?

**Comment by jackherbert** [comment]
It'll need to be on the surrounding div (.iscrollcontent) or the body tag if possible

**Comment by whitemx** [comment]
How about now? the .dialogactive is added to the div with iscrollcontent assigned.

**Comment by jackherbert** [comment]
That's perfect, should be fixed now
