### ISSUE TITLE
CSS Controls not shown correctly in every theme

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#375]
Steps to reproduce:
1. Open CSS Controls from left Views menu.
2. See the page in all the themes (Dark, Light, iOS 7).

Expected result:
I expect all the elements to be correctly formatted.

Actual result:
- In Dark theme Save and Cancel buttons have too little padding in the bottom and Generic and Edit button shapes differ from Save and Cancel button shapes.
- iOS 7 theme Generic and Edit buttons have an unnoticeable, but still visible background colour which I expect should not be there.
  ![img_0284](https://f.cloud.github.com/assets/2638956/2182548/d062e6da-978e-11e3-9811-537fac4df0ee.PNG)
  ![img_0285](https://f.cloud.github.com/assets/2638956/2182549/d06691fe-978e-11e3-901a-1936c6cff9d8.PNG)

**Comment by whitemx** [comment]
Some tweaking required for 3.2 CSS classes

**Comment by jackherbert** [comment]
I fixed the button issues (iOS was insisting on rounded corners and the glare)

Putting the buttons inside a .panel div might be the cleanest way to line up the padding

**Comment by whitemx** [comment]
I've re-jigged the buttons to be inside a panel div which is how they would be used in the real world.
