### ISSUE TITLE
Unplugged release 3.1?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#378]
Hey,

We have been waiting for some time now for functionality of creating documents in another database, as well as a few other features. We were told that these features would be available in February, so I was wondering whether that was part of the 3.1 release? I can see you have recently released some 3.1 code, but i'm not sure if that is the full release or if that is the release we've been waiting for? I was told previously that it would indeed be part of the 3.1 release in February, but my colleague was then told that 3.1 would be released in early April. So i'm a little confused :)

I would just like to know when I can expect to be able to create and edit documents in another database, and if that update will be part of the 3.1 release?

Thanks in advance.

**Comment by whitemx** [comment]
Hi John

Yes this feature was released on Friday as part of 3.1, you can download the latest code along with release notes from http://unplugged.openntf.org

Matt
