### ISSUE TITLE
Creating documents in different database?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#379]
So i've gotten the latest controls (thanks!), but I still seem to have trouble creating documents in another database. I fill out the 'dbname' property of the formviewer. But nothing seems to happen. Instead it simply creates a document in my current database. My formEditor looks like this:

<unp:unpFormEditor showbuttons="yes" viewxpagename="unpMain.xsp"
        formname="formVisit" title="Edit Besøg" xp:key="facet_1"
         position="menu-aligned">
         unp:this.dbName<![CDATA[#{javascript:var lastslash = database.getFilePath().lastIndexOf("/");
var dbname = "/"+database.getFilePath().substr(0,lastslash)+"/spp_vi11.nsf";

return dbname;}]]>/unp:this.dbName

I've also tried not computing the dbName, but simply writing it, but that doesn't work either. Am I doing something wrong, or is the problem at my end?

The document it creates in the current database has 'dbName' as a field. I think it's strange that it would go ahead and create this document when i specifically give it another DB. Or is this something it does if it can't find the dbName?

Thanks and advance.

**Comment by whitemx** [comment]
Could I just confirm that you have updated the UnpSaveDocument XPage in your application? If you have then it looks like we probably have a bug. I am out of the office today but will try and get to look at it tomorrow and let you know how I get on. One thing to try in the meantime would be to see if the database is in the root of the server, whether that would work.

**Comment by JohnCavil** [comment]
Now that you say it I think the issue could be with UnpSaveDocument. I'm pretty sure i've updated it, but we've made a change or two in that xpage a while ago (and in the new one too), so I will try to use the normal one without any modifications. It's probably just one of our minor changes that inferferes with the new version somehow. Unfortunately I cant check until sunday, but i'll let you know if that was the problem, i'm sure it was. Dont want to make you think there's a bug when it's most likely just me overlooking something :)

Thank you.

**Comment by whitemx** [comment]
The other thing to make sure on this is the format of the database path you are writing to. The example of this can be seen in the DocumentEdit XPage in the UnpluggedCustomControlsLibrary database:

```
dbName="teamstudio/widgets/teamroom.nsf"
```

**Comment by JohnCavil** [comment]
I have now updated and fixed UnpSaveDocument which did fix a few things. Unfortunately the documents still arent being created, and i suspect the reason being that "dbother" is undefined.

Right in the start of UnpSaveDocument:

var dbother:NotesDatabase = session.getDatabase(database.getServer(), context.getUrlParameter("dbname"));

When i check what dbother is it just says dbother = "undefined". That seems to be what is causing the error.

My dbname is:
dbName="/Unplugged/spp_vi11.nsf"

The full url of the server is "WWW1/SERVERS/E-CAMPLUS\Unplugged\spp_vi11.nsf". I have tried to alter the url many times, as that has given us problems before, but it doesnt seem to work. We also use the database url in other places in the code where it works fine, so I dont think the url itself is wrong. As far as I can see it is also in the same format as you described.

The database is not at the root of the server, and I dont think it is possible for us to move it. Could that be the problem? Or could it be i'm missing some file/xpage (although i'm very sure i've updated everything).

Thanks again.

**Comment by whitemx** [comment]
Hi John,

I've just re-tested our dev databases and it's all working correctly for me. The only thing I can spot with your dbName property is the forward slash at the start, my setting is this: dbName="teamstudio/widgets/teamroom.nsf"

The design elements which matter for this function are unplugged.js, UnpSaveDocument plus your XPage which contains the UnpFormEditor control. So as long as they are all up to date then I think I'll need to take a look at the nsf to be able to help any more.

Matt

**Comment by JohnCavil** [comment]
Hey just wanted to say that i figured out what the error was.

In unpSaveDocument the method database.getServer() doesnt work for us. We have to leave a blank string for it to work. Quite strange.
