### ISSUE TITLE
SwipeView multiple databases?

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#380]
Hey again,

We have been trying to view images from another database with the SwipeView control, though we don't seem to be able to.

Is it possible to view images stored in a field (multiple images stored in one field) from another db, in a swipe view? We have been able to view images from the same database without any problems.

**Comment by whitemx** [comment]
At the moment that is not possible without modifying the Swipe View control yourself, but I will make sure it's added to the list for 3.2
