### ISSUE TITLE
QuerySaveDocument events not executed...

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#383]
Apparently QuerySaveDocument events are ignored... The tests I ran tend to show that QuerySaveDocument events are executed by Unplugged but they are ignored when Mobile Controls are used...

**Comment by whitemx** [comment]
Hi Ady,

Yes that's right, the documents that are saved with the controls use an XAgent approach which allows for the performance we are looking for. If you want to do a full document save, with the the querysavedocument event then simply disable the standard Save and Cancel buttons (with the property on the UnpFormEditor control) and then add your own buttons to perform the save of document1.

Hope this helps.

Matt
