### ISSUE TITLE
[Dashboard] Different data is displayed when switching between view modes

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#384]
Environment:
version 3.0.1
iPhone 5 (7.1)

Steps to reproduce:
1. Open Dashboard
2. Switch between different view modes (dark, light, iOS 7)

Expected result:
Displayed data is the same

Actual result:
Data is different
![dashboard pie chart](https://cloud.githubusercontent.com/assets/2638956/2547226/b9256006-b64c-11e3-9e33-40817d467cce.jpg)

**Comment by whitemx** [comment]
This is working as designed. The data gets randomly generated whenever the charts are reloaded, the charts get reloaded when switching themes, changing orientation or reloading the page.
