### ISSUE TITLE
Flat View - data rows not tall enough on iPhone

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#39]
The rows containing the 'tappable' data need to be 50%-100% taller. I do not have large hands and was struggling with this :-)

**Comment by whitemx** [comment]
I was asked by Steve to make them smaller. Add this one to the list to talk
about on the next call?

On 10 December 2012 16:18, RichSharpe notifications@github.com wrote:

> The rows containing the 'tappable' data need to be 50%-100% taller. I do
> not have large hands and was struggling with this :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/39.

## 

_Matt White_
Phone - +44 (0) 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 45 Tivoli Road, London, SE27 0ED

**Comment by sives** [comment]
Rich - I'm bringing in Jack Herbert for a session with Matt and I tomorrow to polish up various aspects of the UI, so let's push the fixing of all the UI issues into this phase of work.

**Comment by sives** [comment]
I would regard the "ideal" row height for the specific device as the height used by commonly used native apps on the device e.g. ideal row height for iOS = row height of iOS Contacts app

**Comment by whitemx** [comment]
Make the rows the same height as the iOS Contacts apps.
