### ISSUE TITLE
Cannot delete databases on Android.

### ISSUE THREAD

**Issue by JohnCavil** [unplugged/unplugged-controls#391]
Sometimes on Android when i go to delete a database i'm not able to scroll down in the list of databases and therefore cant delete the database on the device. This only seems to be an android issue.

**Comment by whitemx** [comment]
This sounds like an Unplugged issue. I have reported on to Mark Dixon.

**Comment by adnamsale** [comment]
Hi John,

This is an issue with the database list in current versions of Unplugged on Android. For the upcoming Unplugged 3.1 release we have rewritten most of the UI to use Android native controls and that fixes this issue. If you're interested in being a beta tester for 3.1 then drop me a line (mark_dixon@teamstudio.com) and I'll add you to the list.
