### ISSUE TITLE
[UI Elements > Accordion] One notification for all mandatory fields

### ISSUE THREAD

**Issue by KristelViidik** [unplugged/unplugged-controls#392]
Environment:
version 3.0.1
iPhone 5 (7.1)

Steps to reproduce:
1. UI Elements > Accordion
2. Open any document
3. Click edit
4. Empty all fields
5. Click Save

At the moment there are 3 fields that are mandatory and notifications are displayed one at the time.
Only one notification displays which fields are mandatory.

Is that expected result or is it a bug?
![notifications](https://cloud.githubusercontent.com/assets/2638956/2650997/270d78e8-bf7f-11e3-9383-67cdbde062af.jpg)

**Comment by whitemx** [comment]
This is an expected result.
