### ISSUE TITLE
Capture tap in top menu bar in iOS to scroll to top

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#395]
Request from Mick Moignard:

He [the boss] likes the iPhone thing that if you tap the top line on the screen - the iPhone's connectivity line, some apps will scroll back to the top of the current page.  I  wasn't aware of this one myself, but can see that it works in iOS mail, and one some pages in Safari (bbc.co.uk, for example,  but has to be tapped twice).  He's asking if Unplugged and/or unplugged apps can do that where a scrollable list is displayed.

**Comment by RichSharpe** [comment]
Yeah, this is handy. It works in any mobile web-app so any mobile-web app using our Controls should have this ability. This does not work for Unplugged though as it is embedded in the applications themselves. We need to pass this one over to the Unplugged team for Unplugged apps.
Putting something in the UnpHeader is (IMO) not the best thing to do here.

**Comment by whitemx** [comment]
Seems to be working for me in iOS7
