### ISSUE TITLE
TabbedFooter - Icons from font-awesome do not show in web browser version

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#401]
This works in Unplugged but in a Mobile Web Browser the icons do not appear in the tabs - the error message is:
fontawesome-webfont.woffGET http://localhost/demo/TabbedFooterDemo.nsf/xsp/.ibmmodres/.css/fontawesome-webfont.woff?open&v=4.0.3 404 (Not Found)
fontawesome-webfont.ttfGET http://localhost/demo/TabbedFooterDemo.nsf/xsp/.ibmmodres/.css/fontawesome-webfont.ttf?open&v=4.0.3 404 (Not Found)
fontawesome-webfont.svgGET http://localhost/demo/TabbedFooterDemo.nsf/xsp/.ibmmodres/.css/fontawesome-webfont.svg?open&v=4.0.3 404 (Not Found)

To recreate display a tabbedfooter in Unplugged and then preview in Safari

I copied the font-awesome files in Files and put them in the unp/ psuedo folder (as in the Sampler demo)

**Comment by whitemx** [comment]
The Sampler does work in a web browser, so there'll be some configuration difference. If you can send over the database I'll have a look.

**Comment by whitemx** [comment]
My guess would be that the runtime optimised JS and CSS is enabled in the XSP Properties.

**Comment by RichSharpe** [comment]
D'oh! Gets me a few times a month!?!?!?
