### ISSUE TITLE
TabbedFooter - ajaxtargetid is not defined as a custom property

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#403]
In the CC the code looks to open a page via AJAX from the menuItem.ajaxtargetid (line 53). The doc states that the TabbedFooter will open pages via AJAX but this is not the case as without this, the page opens as a full refresh.

**Comment by whitemx** [comment]
Yeah at the moment the documentation is wrong, the tabbed footer will always do a full page refresh.

**Comment by whitemx** [comment]
I've removed the reference to ajaxtargetid in the tabbedfooter control.
