### ISSUE TITLE
Android UnPlugged Camera Upload Issues

### ISSUE THREAD

**Issue by edm00se** [unplugged/unplugged-controls#405]
BLUF (Bottom Line Up Front): Android UnPlugged app/client isn't working as expected with camera/image upload control.

It was reported to me by a user that the camera/image control wasn't working correctly. After confirming on a physical device (HTC Droid DNA), I found that the behavior which works fine in iOS (6-7.1.1, UnPlugged app and Mobile Safari) does not work in the UnPlugged app on Android only; the native web browser and Chrome both perform as expected.

I was able to re-create the situation in a clean NSF. It's a copy of the unplugged/unplugged-controls at v.3.2 (master branch). I added a camera/image xp:fileUpload control to the UnpDemoFormEditor XPage (no other major changes). Please reference [this commit](https://github.com/edm00se/UnpAndroidCameraWeirdness/commit/bce8ac0969ef5b6cece13a99d9efd488bac39a89) from the [copied NSF](https://github.com/edm00se/UnpAndroidCameraWeirdness) I used for clean verification. By all means feel free to contact me if I can help further dive into this; use my company email (Richard Sharpe should have it) or my GH account.

The controls are working great in our production files otherwise!

**Comment by RichSharpe** [comment]
The issue was actually one from Android with the way the fileUpload controls works in native apps using the embedded webview control  (this is what Unplugged uses). This should have been resolved in the Unplugged 3.1 client release. Please ensure your users (and server) are upgraded and let me know if you are still finding issues on KitKat.

**Comment by edm00se** [comment]
The user's phone is running Android 4.4.2 (KitKat), the controls are the 3.2 controls, so it seems that the culprit is our Data Synchronizer file, as it's at version 3.0.22.564. I'm upgrading that now and will confirm its status following.

**Comment by edm00se** [comment]
I've updated my Data Synchronizer file to v. 3.1.22.683 (both unplugged.nsf and UnpluggedLog.nsf) and tested from the [same current/master copied file](https://github.com/edm00se/UnpAndroidCameraWeirdness) referenced above, on the same Android (4.4.2) device (synced fully from Workspace before trying) and am getting the same results (white screen with file name <numericId>.jpg). Is there something else I can try?

**Comment by RichSharpe** [comment]
Hi Eric,
Just to confirm you updated the client app from the Play store as well (on your device)?
What version of the unplugged client are you running?

**Comment by edm00se** [comment]
Rich,

The Android client app from the Google Play store is reporting v. 3.1.22.683 (which should be current, according to the [Google Play store page](https://play.google.com/store/apps/details?id=com.teamstudio.unplugged.platform.android)).

**Comment by RichSharpe** [comment]
This is a bug in Unplugged and has been reported to the dev team. I will contact them for information of an expected maintenance release

**Comment by RichSharpe** [comment]
Hi Eric.
This is fixed in Unplugged now and is queued for general release to the Play Store. For testing you and your users can download the Android client. Open a browser on the device and go to:
http://unpluggeddemo.teamstudio.com/Unp3Android.nsf/Unplugged-release.apk 
This link will download the apk file directly.
I'll comment on here once the updated version has been accepted and deployed to the Play Store.

**Comment by RichSharpe** [comment]
I should have added: There is another issue that came to light while testing this:  KitKat also added some new file/document system, so if you choose to pick an existing image it presents you with a documents folder, recent, or favorites.  Of course these don't work... they throw a security / access exception when you try to save the document.  Workaround for now is to continue to navigate into Gallery to choose the image, which still works as before.  We're investigating fixes for this one

**Comment by edm00se** [comment]
Excellent news! I'll see about having a couple of my users test with that apk and we should be able to confirm that life is good. I'll push the word down my food chain about using Gallery for existing images.

**Comment by RichSharpe** [comment]
Don't forget that users will have to go into settings and select the 'download from Untrusted Sources' for this beta. One installed, they can turn this off.

**Comment by edm00se** [comment]
I can confirm this is fixed in the updated client app/apk (link above). Thanks for getting the fix out there guys!
