### ISSUE TITLE
DateTimePicker - Time only problem on Unplugged

### ISSUE THREAD

**Issue by andikress** [unplugged/unplugged-controls#407]
Hi,
we are developing an app were our technicians can add activities to an ticket.

Therefore they need to choose a date and also the work start time. These should be handeled with to different fields/selections.

For the Date selection we get it running, for the time selection we only get it work via web browser. In Unplugged only a text editbox will be displayed.

Maybe anyone has a running time selector?

Here ́s the code which is not working on unplugged:

<xp:inputText value="#{Activity.work_start}" id="work_start1"
    style="margin-top:10.0px">
    xp:this.converter
            <xp:convertDateTime type="time" pattern="HH:mm">
            /xp:convertDateTime
    /xp:this.converter
    xp:this.defaultValue<![CDATA[#{javascript:sessionScope.work_start1
    }]]>/xp:this.defaultValue
    xp:dateTimeHelper/xp:dateTimeHelper
/xp:inputText

Here ́s the code for the date picker which is working correct:

<xp:inputText value="#{Activity.date}" id="dateTimeHelper"
    styleClass="xspInputFieldEditBox" type="date">
    xp:this.converter
        xp:convertDateTime
            xp:this.pattern<![CDATA[${javascript:if (Activity.isEditable()){
return "yyyy-MM-dd";
}else{
return "dd MM yyyy";
}}]]>/xp:this.pattern
        /xp:convertDateTime
    /xp:this.converter
    xp:this.defaultValue<![CDATA[#{javascript:if(sessionScope.dateTimeHelper == ""){
return @Today();}else{
return sessionScope.dateTimeHelper}}]]>/xp:this.defaultValue
/xp:inputText

**Comment by whitemx** [comment]
Hi,

This sort of question should now be asked on Stackoverflow with a tag of teamstudio-unplugged

Have you tried setting the type of the field to "time"?

Matt

**Comment by andikress** [comment]
Hi, ok thanks. reposted on stackoverflow...
Yes, i already tried it with type = "time" without any success.
