### ISSUE TITLE
Bug in closing out of UnpFormEditor in Sampler app

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#408]
Open the app and go to the Contacts.
Open a contact and edit then save. The FormViewer XPage should be displayed. If you then click close the app should go back to the Contacts list, instead it goes back to the UnpFormEditor XPage you've just updated.
Occurs on both Android and iOS

**Comment by MartinPerrie** [comment]
Not just the Sampler app - I get the same behaviour in my app. Same symptoms as https://github.com/unplugged/unplugged-controls/issues/357 - although that was fixed as a documentation issue.
