### ISSUE TITLE
Mobile Controls: Loading button don´t work

### ISSUE THREAD

**Issue by StefanUnbehauen** [unplugged/unplugged-controls#409]
Hello,

when using the unplugged mobile controls, in a view 20 entries were loaded (by default). When i click on the "load more button" (or when i change the settings to "pull" instead of the button) no further entries were loaded,  I have this problem with the Browser (Firefox/Chrome) and with the iPhone.

Do you have any solutions for this issue?

Regards

Stefan

**Comment by whitemx** [comment]
Hi Stefan,

If you could log these sorts of issues on Stackoverflow with a tag of teamstudio-unplugged, that would be great thanks.

There are quite a lot of things which could be causing this:
- Have you added the Unp|FlatViewList XPage to your application?
- Is there an error in the console of Chrome or Safari when you're testing? This will most likely point to the source of the problem

Matt

**Comment by whitemx** [comment]
Seems like this issue has been resolved on Stackoverflow: http://stackoverflow.com/questions/24008550/unplugged-mobile-controls-loading-button-dont-work
