### ISSUE TITLE
Calendar control issues

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#417]
Calendar control needs a time of day indication down the left hand side (Google Calendar on Android has a nice compact way to do this)
It also needs to be properly styled.
Also the font size needs to be adjusted to make better use of the screen area and improve legibility

**Comment by whitemx** [comment]
This is certainly an option to enable in the calendar, but I had chosen not to, as when it is enabled, you end up with two scrollable areas which is quite confusing. I recorded a little video to try and show what it would be like: http://londc.s3.amazonaws.com/CalendarScrolling.mp4

**Comment by sives** [comment]
Looking much better now.   

Scrolling behaviour between the all-day panel and the main during-day panel is inconsistent on iPad.  Sometimes the two panels scroll as a single unit and sometimes they scroll independently of each other (which is the desired behaviour) depending upon which week you choose in the week view.

**Comment by whitemx** [comment]
This was basically the issue that caused me to not show the agenda views. The only other solution to this is to disable independent scrolling between the all day and timed events so that the whole calendar scrolls. This is the change I have pushed up now.
