### ISSUE TITLE
Problems with UPMark test screen on Android phones

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#420]
There are two problems:
1. User cannot see the progress indicator at the bottom of the screen because the blurb at the top obscures it - suggest we put the progress indicator above the blurb area

2 The test results will not scroll properly on my Android phone screen - I can only see the first three timings in the table

**Comment by sives** [comment]
Progress bar and scrolling issues fixed but on my Android phone the results table isn't rendering quite right.

![upmark results screenshot](https://cloud.githubusercontent.com/assets/2330529/3200726/f6fa7370-ed7f-11e3-876e-f45b20508384.png)

**Comment by sives** [comment]
See comments above

**Comment by whitemx** [comment]
Resolved this now.
