### ISSUE TITLE
UPmark benchmark needed

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#421]
As per previous releases we need to complete this benchmark to check there are no significant unanticipated performance regressions before we green light this release.

**Comment by whitemx** [comment]
The numbers are pretty much the same (within a 10th of a second) as the previous two versions:

![performance chart](https://cloud.githubusercontent.com/assets/856638/3187404/a288831a-ecb0-11e3-95a5-5f330eaf1e49.png)
![performance stats](https://cloud.githubusercontent.com/assets/856638/3187405/a28ac832-ecb0-11e3-851d-5bff65e4bf78.png)
