### ISSUE TITLE
Text editing panel usability issue

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#422]
The Edit title word at the top of the text panel looks to the user a bit like an active button (even though it is not coloured). The user gets surprised that when you tap on it nothing happens.  Of course this is because nothing should happen - it is a passive label element.  We should change the text from "EDIT" to "TAP ON TEXT TO EDIT" to make this clearer.   

In the next release we should consider replacing this with the newQuill rich text editing control.

**Comment by whitemx** [comment]
Fixed
