### ISSUE TITLE
[Text Editing Panel] - Hard to see the text when editing on Landscape mode

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#426]
**Environment:**
LG Nexus 4 (Android 4.2.2)

**Steps to reproduce:** 
1. Launch the app in Landscape mode
2. Go to Unplugged Sampler
3. Go to Menu ->Typography -> Edit Mode
4. Tap on the text

**Expected result:**
Should have a way to see more text when editing as on Portrait mode

**Actual result:** 
Hard to see the text when editing <p><img src="https://testlio.s3.amazonaws.com/issue/4353/a/2825-medium.jpg"/><br><img src="https://testlio.s3.amazonaws.com/issue/4353/a/2826-medium.jpg"/><br></p>

**Comment by jackherbert** [comment]
Could we hide the Nav bar and any other chrome at the top while the keyboard is present? Might create some valuable extra space

**Comment by whitemx** [comment]
I can certainly hide the header bar in the controls, but in Android there is an application level header bar that I have no control over (this is not present in iOS)

**Comment by jackherbert** [comment]
Seems strange that Android insists on all that chrome when their keyboard is so enormous!

**Comment by whitemx** [comment]
It's exacerbated when people install larger custom keyboards. I guess we'll start to see similar in iOS8 as well.

**Comment by sives** [comment]
The application level header bar is something that Mark Dixon's team can remove in a future version of the Unplugged Engine. I suggest that we just remove the Controls header bar to free up a bit more space and this will have to do for now. The user can always rotate to portrait mode to get a bit more space to work with.

**Comment by unplugged** [comment]
Fixed
