### ISSUE TITLE
[Dashboard] - Sometime, 'Webpage not available' page displays when user taps on Unplugged Sampler

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#433]
**Environment:**
LG Nexus 4 (Android 4.2.2)

**Steps to reproduce:** 
1. Launch the app in Portrait mode
2. Go to Unplugged Sampler

**Expected result:**
Dashboard should displays properly

**Actual result:** 
"Webpage not available" page displays<p><img src="https://testlio.s3.amazonaws.com/issue/4344/a/2814-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
reproducible in HTC One V (4.0.3)

**Comment by whitemx** [comment]
Seems like there is a syncing issue. Also you should be using the application "Controls Sampler", not Unplugged Sampler CSS for testing.

**Comment by unplugged** [comment]
Seems like there is a syncing issue. Also you should be using the application "Controls Sampler", not Unplugged Sampler CSS for testing.
