### ISSUE TITLE
[My Activities] The title and company name can be saved with only white spaces.

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#436]
**Environment:**

iPhone 5s, iOS 7.0

**Steps to reproduce:** 
1. Open menu > Contacts > My Activities
2.  Edit a record, edit the 'title' and 'company' and save them with only white spaces

**Expected result:**

Error/Validation message should be shown.

**Actual result:** 

Able to save with 'title' and 'company' as white spaces.<p><img src="https://testlio.s3.amazonaws.com/issue/4336/a/2802-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
That validation is not being tested. If there is no text in the field then saving is not allowed, but we have simply not implemented a test for whitespace as it may be valid. It would be down to the developer using the controls to implement that as necessary.

**Comment by unplugged** [comment]
That validation is not being tested. If there is no text in the field then saving is not allowed, but we have simply not implemented a test for whitespace as it may be valid. It would be down to the developer using the controls to implement that as necess
