### ISSUE TITLE
[Contacts] Image size for contacts stored can be of same size to avoid UI inconistency

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#438]
**Environment:**
iPhone 5s, iOS 7.0

**Steps to reproduce:** 
1. Open menu > Contacts
2. Scroll through the list

**Expected result:**

All the contact's image size should be uniform and same

**Actual result:** 

Few image sizes are not of the expected size. 

The app itself can manage the image size or while accepting the image, appropriate size can be accepted.<p><img src="https://testlio.s3.amazonaws.com/issue/4332/a/2798-medium.jpg"/><br><img src="https://testlio.s3.amazonaws.com/issue/4332/a/2799-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
In first screenshot, 'Kurt Hoskie' image size is different.
In second screenshot, 'Nelson' image size is different.

**Comment by whitemx** [comment]
This is working as designed, it is down to the developer to decide how to handle image sizes in their data.

**Comment by unplugged** [comment]
This is working as designed, it is down to the developer to decide how to handle image sizes in their data.
