### ISSUE TITLE
[Contacts] If there is no image available for a contact a default image with 'no photo' watermark can be shown

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#439]
**Environment:**

iPhone 5s, iOS 7.0

**Steps to reproduce:** 
1. Open menu > Contacts
2. View a contact without image

**Expected result:**

There can be a default image shown if photo is not available to ensure UI consistency

**Actual result:** 

No photo is shown and the alignment of name is left justified making the UI look inconsistent.

**Comment by whitemx** [comment]
Working as designed. The developer can add a watermark image if it is required.

**Comment by unplugged** [comment]
Working as designed. The developer can add a watermark image if it is required.
