### ISSUE TITLE
Rows not tappable in Flat View or Accordion when wrapped in unpScrollableArea

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#44]

**Comment by whitemx** [comment]
The sample DB you sent me has local access encryption enabled. But I'm not seeing an issue in either the main dev db or in my sample apps for Doc Lib or Teamroom. Is this still an issue?

**Comment by RichSharpe** [comment]
User error :-) demo did not have a div id=content wrapper and you had changed the href to the openDocument js call that loads the doc into this div via AJAX. Fixed in demo.
