### ISSUE TITLE
Change of the display style affects shape of of charts

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#444]
**Environment:**
Samsung Galaxy S3, 4.2

**Steps to reproduce:** 
1. Open Dashboard
2. Press icon at the bottom of the screen (e.g. Light) to change display of background

**Expected result:**
Only background style changes, no effect to the chart.

**Actual result:** 
Charts are affected, more info in attachments. <p><img src="https://testlio.s3.amazonaws.com/issue/4293/a/2768-medium.jpg"/><br><img src="https://testlio.s3.amazonaws.com/issue/4293/a/2769-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
Can not reproduce on iPhone5

**Comment by whitemx** [comment]
added a video<p><a href="https://testlio.s3.amazonaws.com/issue/4293/ca/255/IMG_1488.mp4">IMG_1488.mp4</a><br></p>

**Comment by whitemx** [comment]
There is a known issue with the charts redrawing on Android.

**Comment by unplugged** [comment]
There is a known issue with the charts redrawing on Android.
