### ISSUE TITLE
Typography - Read mode - Minimising text diminishes all of the fonts

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#446]
**Environment:**
Samsung Galaxy s3, 4.3

**Steps to reproduce:** 
1. Go to Typography > Text Reading Panel
2. Press Minus icon several times to minimize text 
3. Maximize the text back

**Expected result:**
After maximizing, font returns to previous size.

**Actual result:** 
After maximizing, all of the fondt are of the same size. <p><img src="https://testlio.s3.amazonaws.com/issue/4291/a/2766-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
Can not reproduce in iPhone5

**Comment by whitemx** [comment]
Can't reproduce on Nexus 4 (4.4.2)

**Comment by unplugged** [comment]
Cannot reproduce

**Comment by unplugged** [comment]
whitemx commented 4 hours ago
Can't reproduce on Nexus 4 (4.4.2)

Closed by customer side
