### ISSUE TITLE
Change of orientation in Unplugged Controls' submenus result with return to previous menu

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#447]
**Environment:**
Samsung Galaxy S3, 4.3

**Steps to reproduce:** 
1. Open menu > UI Elements > Calendar
2. Change orientation of the device
3. Note for being returned to previous menu

**Expected result:**
Orientation of the display changes, but user is kept in the same menu.

**Actual result:** 
User is returned to the Unplugged Controls menu.

**Comment by whitemx** [comment]
can not reproduce on iPhone5

**Comment by whitemx** [comment]
Known issue on Android. This is a duplicate.

**Comment by unplugged** [comment]
Closed by customer side - Known issue on Android. This is a duplicate.
