### ISSUE TITLE
Entries are still shown in favorites, after they was unfavorited 

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#449]
**Environment:**

**Steps to reproduce:** 
1. Open Media - Favorites
2. Tap on any icon
3. Remove Favorite

**Expected result:**
Page refreshes "on the fly"

**Actual result:** 
Pop-up is closed, Favorites page is opened, icon, which is not favorited now is still shown<p><img src="https://testlio.s3.amazonaws.com/issue/4288/a/2764-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
This is working as designed. The idea is that you might unfavorite something by mistake and want to get back to it. Similar to Gmail favourites functionality.

**Comment by unplugged** [comment]
Closed by customer side - This is working as designed. The idea is that you might unfavorite something by mistake and want to get back to it. Similar to Gmail favourites functionality.
