### ISSUE TITLE
Dashboard is always opened after exiting Swipe View

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#457]
**Environment:**

**Steps to reproduce:** 
1. Open Menu > UI elements > Form (Read Mode)
2. Click Close
3. Open menu again > Swipe View
4. Close

**Expected result:**
Form (Read Mode) is opened

**Actual result:** 
Dashboard is opened

**Comment by whitemx** [comment]
Working as designed.

**Comment by unplugged** [comment]
closed by customer - Working as designed.
