### ISSUE TITLE
Text overlaps picture on Swipe View

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#458]
**Environment:**

**Steps to reproduce:** 
1. Open app in landscape
2. Open menu > UI elements > Swipe View

**Expected result:**
Image name doesn't overlap picture on Swipe View

**Actual result:** 
Image name overlaps picture on Swipe View<p><img src="https://testlio.s3.amazonaws.com/issue/4274/a/2748-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
looks a lot better in iPhone5<p><img src="https://testlio.s3.amazonaws.com/issue/4274/ca/254-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
Based on the length of the file name, this is not a big issue.

**Comment by unplugged** [comment]
closed by customer - Based on the length of the file name, this is not a big issue.
