### ISSUE TITLE
Wrong menu item is highlighted when switching form from read to edit mode

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#459]
**Environment:**

**Steps to reproduce:** 
1. Open Menu > UI elements > Form (Read Mode)
2. Tap Edit
3. Open menu

**Expected result:**
Probably, Form (Edit Mode) should be highlighted

**Actual result:** 
Form (Read Mode), but in fact Form (Edit Mode) is opened

**Comment by whitemx** [comment]
The Form Read Mode and Form Edit mode pages are demos that are meant to stand alone. It was decided that having the buttons visible but inactive was wrong, so now they are linked. This is working as designed.

**Comment by unplugged** [comment]
closed by customer - The Form Read Mode and Form Edit mode pages are demos that are meant to stand alone. It was decided that having the buttons visible but inactive was wrong, so now they are linked. This is working as designed.
