### ISSUE TITLE
Wrong menu item is highlighted

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#461]
**Environment:**

**Steps to reproduce:** 
1. Open menu > UI elements > Flat View (Categorized)
2. Open menu > Form (Edit Mode)
3. Scroll down
4. Cancel
5. Open Menu again

**Expected result:**
Opened page is highlighted 

**Actual result:** 
Form (Edit Mode) is highlighted, but Flat View (Categorized) is opened<p><img src="https://testlio.s3.amazonaws.com/issue/4271/a/2747-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
Another one related to how the Read Mode and Edit mode form screens are opened. This can be ignored.

**Comment by unplugged** [comment]
closed by customer - The Form Read Mode and Form Edit mode pages are demos that are meant to stand alone. It was decided that having the buttons visible but inactive was wrong, so now they are linked. This is working as designed.
