### ISSUE TITLE
Flat View Categorized overlaps search field

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#462]
**Environment:**

**Steps to reproduce:** 
1. Open Menu > UI Elements > Flat View
2. Make a search with any query
3. Open menu > Flat View (Categorized)
4. Scroll down a bit

**Expected result:**

**Actual result:** 

<p><img src="https://testlio.s3.amazonaws.com/issue/4270/a/2746-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
This appears to be fixed on my iPhone:
![img_0462](https://cloud.githubusercontent.com/assets/856638/3215759/e6d5a946-efc4-11e3-9295-6fa3c1f18c52.PNG)

**Comment by unplugged** [comment]
Fixed
