### ISSUE TITLE
Dialog has no bottom border

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#465]
**Environment:**

**Steps to reproduce:** 
1. Start app in portrait
2. Open Menu > UI elements > Dialog
3. Tap Open Dialog

**Expected result:**
Dialog is shown with bottom border

**Actual result:** 
Dialog is shown. There is not bottom border<p><img src="https://testlio.s3.amazonaws.com/issue/4267/a/2743-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
its a look better in iPhone5 (7.1)<p><img src="https://testlio.s3.amazonaws.com/issue/4267/ca/253-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
We are targeting iPhone 5+ for these controls.

**Comment by unplugged** [comment]
closed by customer - We are targeting iPhone 5+ for these controls.
