### ISSUE TITLE
Themes icons are aligned incorrectly in Landscape

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#467]
**Environment:**

**Steps to reproduce:** 
1. Start app in Landscape
2. Open Dashboard
3. Observe theme icons placement

**Expected result:**
Theme's icons are centered.

**Actual result:** 
Theme's icons are aligned to the right<p><img src="https://testlio.s3.amazonaws.com/issue/4265/a/2741-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
This is working as designed. The aim is to allow more footer tabs for landscape or tablets

**Comment by unplugged** [comment]
closed by customer - This is working as designed. The aim is to allow more footer tabs for landscape or tablets
