### ISSUE TITLE
Orientation change requires about 30 seconds

### ISSUE THREAD

**Issue by whitemx** [unplugged/unplugged-controls#469]
**Environment:**

**Steps to reproduce:** 
1. Start app
2. Open Dashboard
3. Select Dark theme
4. Change orientation

**Expected result:**
Orientation changes immediately. 

**Actual result:** 
Orientation change requires about 30 seconds to complete. This is unacceptable<p><a href="https://testlio.s3.amazonaws.com/issue%2F4263%2Fa%2F2739%2FIMG_0710.mp4">IMG_0710.mp4</a><br></p>

**Comment by whitemx** [comment]
Orientation change also produce a crash sometimes<p><a href="https://testlio.s3.amazonaws.com/issue/4263/ca/249/Unplugged_2014-06-05-135349_iPhone-maksymma.ips">Unplugged_2014-06-05-135349_iPhone-maksymma.ips</a><br></p>

**Comment by whitemx** [comment]
This is unrelated to the Unplugged Controls. Orientation change is being worked on by the Unplugged dev team.

**Comment by unplugged** [comment]
closed by ctstomer - This is unrelated to the Unplugged Controls. Orientation change is being worked on by the Unplugged dev team.
