### ISSUE TITLE
Error when saving a document in another database

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#487]
UnpSaveDocument gets a handle to the other database using

```
var dbother:NotesDatabase = session.getDatabase(database.getServer(), context.getUrlParameter("dbname"));
```

but Unplugged doesn't support database.getServer(). Should this read

```
var dbother:NotesDatabase = session.getDatabase("", context.getUrlParameter("dbname"));
```

**Comment by whitemx** [comment]
Hi Martin,

Both seem to work for me using the latest version of Unplugged, but I will change it to use the "" just for safety's sake.

Matt
