### ISSUE TITLE
Chevrons in FlatView List do not align correctly in FireFox and IE browsers

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#488]
Chevrons in FlatView List items do not align correctly in FireFox and IE browsers

Original submission in German:
"Pfeil"-Darstellung bei FlatViewList Datensätzen im Webbrowser (aktuellster Firefox, IE 11) seltsam

**Comment by whitemx** [comment]
We don't support IE or Firefox. Basically unless the browser is Webkit based then things will not work correctly.

**Comment by RichSharpe** [comment]
FireFox and IE do not use the Webkit framework in their browsers. The Unplugged Controls are designed to only work with Webkit compatible browsers such as Chrome and Safari.
No plans to fix.

**Comment by sives** [comment]
This will likely change with the upcoming Unplugged Controls 4.x (aka Unplugged Bootstrap Controls) that we are planning for later in the year.  IE 8-11 plus latest versions of Firefox will be supported in this new world.

![bootstrap browser support june 2014](https://cloud.githubusercontent.com/assets/2330529/3288487/1a9858ca-f563-11e3-8084-380965077081.png)
