### ISSUE TITLE
Calendar Control : Full day events not displayed correctly

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#493]
Say you have a 3 full day event starting on 01/mm/yyyy and ending on 03/mm/yyyy. This event is displayed in the calendar as spanning accross 2 days (01/mm/yyyy and 02/mm/yyyy)  instead of 3 days.

**Comment by whitemx** [comment]
For the end date of the event, 00:00 as the time is taken to be midnight. To make the event run for three days you'll want to store 03/mm/yyyy 23:59

**Comment by whitemx** [comment]
We'll improve this in the next version of the controls.
