### ISSUE TITLE
xp:button no longer fire in 3.3

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#497]
If I have regular XP buttons in an XPage I tap on them but the events no longer fire if the controls are used.
I'll send MW a test DB with instructions but a simple test is to create an XPage with a unpListView pointing to an XPage with a UnpFormViewer. Set the editPageWithAjax property to 'No'. Set the EditXPageName to a new XPage.
In the new XPage do not use any controls but list the fields with xp:inputText controls and a [save] xp:button. Run and save. Should work.

Then add a unpHeader in the xpage and re-run. The button no longer works.
I think this _may_ be caused by a change in unpCommon.jss??

**Comment by whitemx** [comment]
This is caused by the Fastclick library. Basically I'm going to need to remove the library for this use case to work. 

Fastclick hijacks button clicks to make them operate faster and in doing so breaks the way that XPages create on click events on buttons.
