### ISSUE TITLE
unpDialog needs a param entry to pass to the callback method.

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#499]
Currently the callback must be a void method. It would be useful to pass through something like the UNID so the CSJS function can be more effective.

**Comment by whitemx** [comment]
I've added a new, empty object called unpdialogoptions that is passed back to the callback function. You can set whatever properties against the object that you like:

``` javascript
unpdialogoptions.unid = 'a unid';
```

Then when the dialog is OK'd the object is passed back to the callback function for you to work with as needed.
