### ISSUE TITLE
Accordion view always expands the first entry.

### ISSUE THREAD

**Issue by mickmoignard** [unplugged/unplugged-controls#502]
<?xml version="1.0" encoding="UTF-8"?>
<xp:view xmlns:xp="http://www.ibm.com/xsp/core" xmlns:xc="http://www.ibm.com/xsp/custom"
    xmlns:unp="http://unplugged.teamstudio.com">

```
<xc:layout> 
    <xp:this.facets>
        <xp:panel xp:key="facet_1">
            <div id="contentwrapper">
                <unp:unpScrollableArea>
                    <xp:this.facets >
                    <unp:unpAccordion insetData="true"
                        viewName="FutureXP"
                        expandfirstcategory="no" xp:key="facet_1" xpage="/WeeklyLog.xsp"
                        dataColumn="3" summaryColumn="2">
                    </unp:unpAccordion></xp:this.facets>
                </unp:unpScrollableArea>
            </div>
        </xp:panel>
    </xp:this.facets>
</xc:layout> 
```

/xp:view
Note the expandfirstcategory="no".

**Comment by MartinPerrie** [comment]
I'm getting the same. I think the problem lies in the "loadpage" function in Unpluggged.js. Looks as if it's calling $('.categoryRow').first().click(); regardless of the value of the expandfirstcategory property.
