### ISSUE TITLE
UnpAccordion not displaying documents after opening & closing a document

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#509]
I'm using the accordion to display a view from another database. As noted by Mick the first category is always expanded (issue #502). If I open a document from that category and then close it to return to the view, the first category shows as if expanded (with a down arrow) but there are no documents shown. If I collapse and then expand the category then the documents are displayed.

**Comment by MartinPerrie** [comment]
Not sure I can recreate this now - although it seemed to be happening consistently when I reported it. Not sure what has changed to "fix" it. Unless you are aware of an issue I'd be tempted to close this and I'll report back if I find it occurring again.

**Comment by whitemx** [comment]
Thanks Martin. I hadn't been able to reproduce this myself either.
