### ISSUE TITLE
Checkbox always generates "on" and "off" values

### ISSUE THREAD

**Issue by mickmoignard** [unplugged/unplugged-controls#512]
I have a checkbox:
<xp:checkBox text="" id="NoCallsMonday" 
value="#{document1.NoCallsMonday}"
required="false" styleClass="xspCheckBox" 
uncheckedValue="#{javascript:''}" 
checkedValue="No Calls">
/xp:checkBox

which always generates "on" and "off" values in side an UnformEdit.  Works OK when on an Xpage by itself. I see Martin in 511 suggests that it can be made to work.

**Comment by mickmoignard** [comment]
Do I need to follow his example and use specific attributes?

**Comment by whitemx** [comment]
The short answer is yes, you need to add the attributes to the control that specify the on and off values:

The "FormsEditMode" XPage in the Sampler app gives the following as an example of a mobile switch control :-

``` xml
<li>
    <xp:label value="Mobile Enabled" for="mobileenabled"></xp:label>
    <div class="switch">
        <xp:checkBox text="" id="mobileenabled"
            checkedValue="on" uncheckedValue="off"
            value="#{document2.mobileenabled}" required="false">
        </xp:checkBox>
    </div>

</li>
```

which is fine if using the default "on" and "off" values. But if you want to use alternate values (e.g. "1" and "0") then the checkedValue and uncheckedValue need to be specified as attributes so the code at the top of unp.SaveDocument can pick them up. E,g,

``` xml
<li>
    <xp:label value="Mobile Enabled" for="mobileenabled"></xp:label>
    <div class="switch">
        <xp:checkBox text="" id="mobileenabled"
            value="#{document2.mobileenabled}" required="false">
            <xp:this.attrs>
                <xp:attr name="checkedValue"
                    value="1">
                </xp:attr>
                <xp:attr name="uncheckedValue"
                    value="0">
                </xp:attr>
            </xp:this.attrs>            
        </xp:checkBox>
    </div>

</li>
```

**Comment by mickmoignard** [comment]
While that sorta works, I have the issue where one of teh values I want to use is "": Empty. Tim C gave me this to use: uncheckedValue="#{javascript:''}" but I can't make it work in the context of unpFormEditor.
