### ISSUE TITLE
[Orientation] does not work properly in Dashboard

### ISSUE THREAD

**Issue by unplugged** [unplugged/unplugged-controls#515]
**Environment:**
Unplugged Controls v3.4, Moto G on Android 4.4.4

**Steps to reproduce:** 
1. Navigate to dasboard and turn the phone 90 degrees to view landscape view
2. Return to portrait view

**Expected result:**
Portrait view should be displayed

**Actual result:** 
Portrait view shows up in half the screen in a few seconds (5 to 10 seconds)<p><img src="https://testlio.s3.amazonaws.com/issue/9305/a/5164-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
In my testing on Android, the orientation change does happen, but it takes a while. This seems to be a limitation of Android. Could you confirm if the orientation change never happens or just takes a long time?

**Comment by unplugged** [comment]
working fine on iPhone 5s

**Comment by unplugged** [comment]
Comment from client:
In my testing on Android, the orientation change does happen, but it takes a while. This seems to be a limitation of Android. Could you confirm if the orientation change never happens or just takes a long time?

Manas, can you take a look at the question client has

**Comment by unplugged** [comment]
Let me retest it

**Comment by unplugged** [comment]
Orientation change happens but takes a while before it displays correctly.

**Comment by whitemx** [comment]
OK this is out of my control, it's an Android thing.

**Comment by unplugged** [comment]
Closed from GitHub
