### ISSUE TITLE
Accordion doesn't keep the same view when returning from document view

### ISSUE THREAD

**Issue by unplugged** [unplugged/unplugged-controls#516]
**Steps to reproduce:** 
1. Open Accordion from left menu Views.
2. Select UK category.
3. Click on a document.
4. Click Close document.

**Expected result:**
I expected to see the same category open and scrolled in same place so I could continue working with the list.

**Actual result:** 
The first category is opened again instead.

**Comment by unplugged** [comment]
Same issue found on  - Cancel from document; It does not returns to view. Tested - Moto G android 4.4.4

**Comment by whitemx** [comment]
This is a known issue.
