### ISSUE TITLE
[Calendar] Week format is bad

### ISSUE THREAD

**Issue by unplugged** [unplugged/unplugged-controls#520]
**Environment:**
v3.4

**Steps to reproduce:** 
1. UI Elements > Calendar
2. Tap Week

**Expected result:**
The appointments to be displayed well.

**Actual result:** 
Some appointments have width of 3mm which makes it quite hard to be clicked.<p><img src="https://testlio.s3.amazonaws.com/issue/9278/a/5156-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
What device is being used here? When I view the week Jul-20-26 on an iPad in portrait I see the following: 
![img_0450](https://cloud.githubusercontent.com/assets/856638/3700552/46e80ca2-13e2-11e4-8381-bfff0a8f6be7.PNG)

**Comment by unplugged** [comment]
Comment from client:
What device is being used here? When I view the week Jul-20-26 on an iPad in portrait I see the following: <p><img src="https://testlio.s3.amazonaws.com/issue/9278/ca/484-medium.jpg"/><br></p>

**Comment by unplugged** [comment]
Apple iPad 2 Wi-Fi iOS 7.0 (listed below Devices on the side)

**Comment by whitemx** [comment]
I can't reproduce this now so I must have fixed it inadvertently.

**Comment by unplugged** [comment]
Closed from GitHub
