### ISSUE TITLE
[Dialog] - Scroll bar is not appearing in demo dialogue 

### ISSUE THREAD

**Issue by unplugged** [unplugged/unplugged-controls#524]
**Environment:**
Samsung Galaxy Tab 2 10.1 Android 4.1.1

**Steps to reproduce:** 
1. Click on open dialog
2. Observe demo dialog

**Expected result:**
scroll bar should appear

**Actual result:** 
if content is more scroll bar is not appearing..

**Comment by unplugged** [comment]
attached screenshot.. <p><img src="https://testlio.s3.amazonaws.com/issue/9325/ca/444-medium.jpg"/><br></p>

**Comment by whitemx** [comment]
This seems to be a design decision we made with all Android scroll bars (e.g. Flat view has no scroll bars either). So this is working as designed.
