### ISSUE TITLE
[Text Editing Panel] Cannot edit the existing text.

### ISSUE THREAD

**Issue by unplugged** [unplugged/unplugged-controls#533]
**Environment:**
v 3.4

**Steps to reproduce:** 
1. Open Control Sampler > Typography >Text Editing Panel
2. Tap into the existing text

**Expected result:**
The cursor to appear in the tapped position in the text.

**Actual result:** 
The cursor appears at the end of the text. New text can be added, but the existing one cannot be edited.

**Comment by whitemx** [comment]
Initial focus places the cursor at the end of the field (on iOS) or the beginning of the field (on Android). But once you are in the field, you can reposition the cursor and edit text with no problems.
