### ISSUE TITLE
More doc needed for contentwrapper div

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#54]
This is necessary for the ViewList control and is used on the example on the wiki home page but could do with an explanation that it's in the scrollArea control and what it's used for etc.

**Comment by whitemx** [comment]
I've added more documentation in the Wiki, let me know if this makes sense.

**Comment by sives** [comment]
Rich to look at the current doc that Matt has just prepared and give feedback, Matt to amend document if necessary.

**Comment by RichSharpe** [comment]
Fixed - beta testers will feed back on other doc issues.
