### ISSUE TITLE
Typeahead always defaults to the first name listed

### ISSUE THREAD

**Issue by AdyMakombo** [unplugged/unplugged-controls#540]
In a field with typeahead enabled, when a user clicks on any of the names in the drop-down, on the next screen it always defaults to the first name listed (in this case Jill Stuber in the screen shot). The Company field in the Sampler app has the same behavior. 

Is this how the type-ahead feature is supposed to work or is this a bug?

![image1](https://cloud.githubusercontent.com/assets/3041329/6623670/a1b705f4-c8e4-11e4-9806-4823f53ae35c.PNG)
![image2](https://cloud.githubusercontent.com/assets/3041329/6623671/a1bae12e-c8e4-11e4-939a-c43b3308239a.PNG)

**Comment by whitemx** [comment]
This will be fixed in XControls
