### ISSUE TITLE
UnpFormEditor - Date fields not saving when converter applied

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#59]
I tested the date conversion on a simple app to ensure this is working on Unlpugged (It is):
xp:this.pattern<![CDATA[${javascript:return "yyyy-MM-dd";
}]]>/xp:this.pattern

and the doc is updated on a regular file save. 
However in the UnpFormEditor control the date is not save and the original is displayed after a save event.

**Comment by whitemx** [comment]
I'll need to have a look at the code to work out what the problem is here. Could you send me an example?

**Comment by RichSharpe** [comment]
Journal Template has an example in DocumentEdit.xsp

**Comment by whitemx** [comment]
It's working fine for me, the only change I made was to update the ID of the DiaryDate field (it's the ID which is used by the Ajax XPage to save the field onto the document).
