### ISSUE TITLE
Header shows new Views button when declared as false in property definition

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#60]

**Comment by whitemx** [comment]
Not seeing this issue. Have you got an example? (Worth noting that the Back and Views buttons look the same now!)

**Comment by RichSharpe** [comment]
Ahh this is what confused me. Do we want these buttons to look the same? (Back and Views?) This really confused me and I thought when I tapped the 'Views' button - expecting the views list of categories, it went 'back' to the workspace (by design) and I thought my app had crashed. Personally I think we should have different UI for different buttons?

**Comment by whitemx** [comment]
I think you're probably right, but it will need UI love from Jack. Also,
I've ended up not using Back at all in my templates so not sure how urgent
it is.

Matt

On 24 December 2012 14:49, Rich Sharpe notifications@github.com wrote:

> Ahh this is what confused me. Do we want these buttons to look the same?
> (Back and Views?) This really confused me and I thought when I tapped the
> 'Views' button - expecting the views list of categories, it went 'back' to
> the workspace (by design) and I thought my app had crashed. Personally I
> think we should have different UI for different buttons?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/60#issuecomment-11661678.

## 

_Matt White_
Phone - +44 (0) 7767 384970
E-Mail - matthew.white@fclonline.com
Personal Blog - mattwhite.me

## Twitter - @mattwhite http://twitter.com/mattwhite

Fynn Consulting Ltd http://www.fclonline.com is a limited company
registered in England & Wales with registered number 4014250

## Registered office address at 45 Tivoli Road, London, SE27 0ED

**Comment by unplugged** [comment]
Lets sort thiss one out with a call and discussion after Xmas when we are back from the break. Can you both make a Skype call on either 27th or 28th, say 3pm London time?
BR
Steve

**Comment by whitemx** [comment]
Hi 

28th is good with me. I will have the workspace control done by that point as well.

Matt

**Comment by whitemx** [comment]
I will create a back button with the word "Back" to fix this.
