### ISSUE TITLE
UnpFormViewer - If more that one <xp:text> is in an <li> it is not grouped and the separator appears between the items  

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#65]
For example if I have
<li>
xp:label.... name .... /xp:label
xp:text ... first name ... /xp:text
xp:text ... last name ... /xp:text
</li>
the separator will be between the first name and the last name.

**Comment by RichSharpe** [comment]
Should have added that this occurs in FormEditor as well and the additional contents overlap the next area.

**Comment by whitemx** [comment]
As far as I know this is working as designed, in that case you should have a second li and label for the last name field.
