### ISSUE TITLE
List view item height on iPhone in landscape

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#68]
On my iPhone 5, list view items are the correct font size and item height when viewed in portrait mode, but when you switch into landscape mode the font size and the item height are significantly increased.  They should stay the same size between these 2 modes.  (seems to be an issue with the iPhone 5 landscape mode being recognised by Unplugged as a small tablet).

**Comment by whitemx** [comment]
I've tested on every device that I have to hand and am unable to see any difference between the row heights in landscape and portrait. Could you send me some screenshots so that I can try and diagnose the problem?

Thanks.

**Comment by sives** [comment]
I've just emailed some screenshots to Matt and Rich
