### ISSUE TITLE
UnpFlatView - view refresh not working

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#79]
Using the Unplugged controls to mobilise one of my own apps.  The refresh of the flat view to load more items is not working. I _think_ this may be an error in the "loadmore" function which has a hard-coded reference to "UnpFlatViewList.xsp".

**Comment by whitemx** [comment]
Hi Martin,

That XPage is required for the flat view to work. It is called via Ajax to load the next chunk of data to be displayed. You shouldn't need to do anything more than just copy the XPage into your database.

Matt

**Comment by MartinPerrie** [comment]
Hi Matt

Thanks for that - it works once I copied the XPage over. 

I can see (now!) that this is documented in the Wiki, but it doesn't mention it in the Design Definition of the "unpFlatView" custom control - which is more obvious when coding.

As an aside, maybe we should have a "Documentation" label available for issues?

Martin

**Comment by whitemx** [comment]
I've added a new documentation label as well. Thanks for the feedback.
