### ISSUE TITLE
UnpFormViewer - button visibility

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#81]
Hi Matt,

Couple of things on the UnpFormViewer :- 

I couldn't get the buttons to be hidden, even though I have set the property "showbuttons" to false. Whilst looking at the code in the custom control I noticed that the rendered property (compositeData.showbuttons == true), was defined as expression language. If I change this to Javascript, then the custom property seems to take effect and the buttons are hidden. Am I missing something else?

More of an enhancement - would it be possible to hide / show the "New Response" button independently of the others? I might want to display the "Edit" & "Close" buttons but not the "New Repsonse" button. Could possibly use the "newresponsexpagename" to control this - if it's an empty string then don't show the button. Any thoughts?

Martin

**Comment by RichSharpe** [comment]
The New Response button should only be shown if the newresponsexpagename custom property is set. I tested this and the button gets rendered even when this field is empty.
