### ISSUE TITLE
Documentation on Wiki/Design Def

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#82]
unpHeader

unp/icon_19.png referenced in the unpHeader in docs not in db

unpSearchResults

I don't see in the docs to include the script libraries unpSearchDatabase and unpSearchLocal

I don't see in the docs anywhere desribed what config the search view should have

**Comment by whitemx** [comment]
I've updated the Wiki for unpHeader and for the view format for unpSearchResults. The unpSearchDatabase and unpSearchLocal are required by unpHeader, but not by unpSearchResults.
