### ISSUE TITLE
File Upload Control not working in unpFormEditor

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#83]
I use a file upload control and it appears on the screen. I choose a picture and I can see the thumbnail - nothing is saved to the back end doc....

**Comment by whitemx** [comment]
If the file is uploaded as binary (in the same way it works on the Internet) then this can't work with the unpFormEditor as we use Ajax to submit the data and Ajax can't handle binary data. If you wanted to have a file upload control that would need to be handled with your own "proper" submit button that does a full page refresh afterwards. 

To do this I would disable the Save and Cancel buttons and add my own Submit button.
