### ISSUE TITLE
Backend combo-box fields on forms do not save correctly from XPage bindings

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#84]
In a UnpFormEditor Control I have a form with a Combobox called Dept. My XPage has:
xp:listBox id="multi_dept" value="#{document1.Dept}"
xp:selectItem itemLabel="IT" itemValue="IT" /xp:selectItem
xp:selectItem itemLabel="Sales" itemValue="Sales" /xp:selectItem
/xp:listBox

(I had to remove the tags)

When I save the new doc the entry does not get inserted into the back end doc. 
Other simple xp:text types for the same doc get saved fine.

**Comment by whitemx** [comment]
The listBox id needs to be in the format "multi__dept" (ie with two underscores, as I wanted to make it as unlikely as possible that there would be an existing field that would match that pattern).

You can see examples in the DocumentEdit.xsp in the Teamroom template.

Matt
