### ISSUE TITLE
UnpViewsList

### ISSUE THREAD

**Issue by MartinPerrie** [unplugged/unplugged-controls#85]
1. Documentation : UnpViewsList requires the image resource unp/right-arrow-trans-white-large.png
2. Question: the properties ajaxloadid and ajaxcontentid both default to "results" - I wasn't sure where "results" comes from. Would it be better if these properties defaulted to "contentwrapper" and "content" respectively, to tie in with the scrollable area and the "content" <div> on UnpMain?

**Comment by whitemx** [comment]
I have updated the wiki to reflect the extra graphic which is required.
