### ISSUE TITLE
Template problems on Android

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#88]
I synced up my Google Nexus 7 (running Android 4.2, kernel 3.1.10, build number J0P40C) to the Londondevelopercoop Unplugged server and synced the 6 databases.

When I open up any of the templates (Doc Lib, Teamroom or Journal) I get a white unformatted screen with the list of main views for that template.

I looked at my version of Unplugged and saw that it was on 2.1.  So I uninstalled it and am now trying to replicate this using the 2.2 version of Unplugged.

**Comment by whitemx** [comment]
Hi Steve,

I've updated my Nexus 7 to the latest public build and it works properly. One caveat was that I had to remove all of the databases and re-sync before they worked properly.

Matt

**Comment by sives** [comment]
Thank Matt, that's good to hear that it works, at least!

On Tue, Jan 15, 2013 at 8:32 AM, Matt White notifications@github.comwrote:

> Hi Steve,
> 
> I've updated my Nexus 7 to the latest public build and it works properly.
> One caveat was that I had to remove all of the databases and re-sync before
> they worked properly.
> 
> Matt
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/88#issuecomment-12257706.

## 

_Stephen Ives_ / Director
*www.hoverkey.com
*Strong mobile security without passwords
