### ISSUE TITLE
unpFlatView: add option to use view from another database

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#93]
I think it would be useful to add a 'databaseName' name property to the unpFlatView control to allow for using a view from an external database.

**Comment by whitemx** [comment]
A good idea, will require changes to UnpFlatView, UnpFlatViewList, openDoc function, unpFormEditor, unpFormViewer, unpSaveDocument. With testing etc this will result in around 8-10 hours effort so my suggestion is that this waits for v1.2 as v1.1 will be released in the middle of next week.

**Comment by sives** [comment]
This seems sensible to me.  However, if it turns out to be on the critical path for the Continuity project we might need to bring it forward.  Let's discuss this afternoon.

**Comment by RichSharpe** [comment]
This will need adding to the UnpAccordion controls also

**Comment by whitemx** [comment]
Issues still to resolve:

1) The accordion view needs to do a @DbColumn to get the list of categories but that seems to fail in Unplugged (works in Java Implementation but not on devices)

2) It does not seem to be possible to set up a document data binding for documents in a different database so as things stand, the view control will work but you will need to open the document using an XPage in the database in which the document resides which makes the new feature a little less useful!

Will revisit when we get the next version of Unplugged to see where we stand.
