### ISSUE TITLE
unpHeader: set "Home" icon link target

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#94]
The Home icon now always opens the Unplugged workspace. Add an option to choose to link to the workspace or the application's startpage (UnpMain.xsp).

**Comment by whitemx** [comment]
My question there would be that if you choose to set the Home icon to open the application start page, how will the user get back to the Workspace?

**Comment by sives** [comment]
In the Continuity app there is no workspace.  Unplugged is set up via a configuration option to load directly into the application start page (which is a customised version of the Unplugged workspace, using the new workspace UI control)

**Comment by whitemx** [comment]
In that case, wouldn't the existing home link effectively take you back to the home screen of the application? The reason I'm pushing back slightly is that I'd like to keep the configuration options for the controls as simple as possible and only add a new option if it's absolutely necessary.

Matt
