### ISSUE TITLE
Idea for possible performance enhancement

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#95]
In web apps you can get a better performance by minimizing the number of (HTTP) requests on a page by combining resources (e.g. JS files, just like the aggregate function in Designer). 

Almost every Unplugged control contains multiple (JS) resources and it's almost every time the same set. I'm wondering if the performance would further increase if you combine those into a single file. After all, Unplugged also uses a WebView to display the generated pages.

**Comment by whitemx** [comment]
We have already merged as much of the JS and CSS into single files as is possible. The current exceptions are for database searching and the less used controls (Dialog and Swipeview). I did experiment with merging the jQuery files together but things started to break fairly quickly!
