### ISSUE TITLE
Flat view demo: changes URL when closing a document

### ISSUE THREAD

**Issue by markleusink** [unplugged/unplugged-controls#97]
If a open a document from the "Flat view demo" (UnpDemoFlatView.xsp) and click "Close", I'm redirected to UnpDemoWidgets.xsp (instead of going back to UnpDemoFlatView.xsp.

**Comment by markleusink** [comment]
BTW: I was able to fix this by adding a parameter (?from=<name_of_xpage>) to the url in the openDocument() call and then using the value of that parameter in the closexpagename property of the unpFormViewer.

**Comment by whitemx** [comment]
The Flat view demo was really to show the view itself rather than it's interaction with the FormViewer control so I have added a new dummy page to deal with this.
