### ISSUE TITLE
Form editable fields issue

### ISSUE THREAD

**Issue by sives** [unplugged/unplugged-controls#98]
Matt,
The appearance of the "edit mode" of the form is too similar to the "read mode".   If you open a document in the "Demo of all widgets", then tap on "Edit", I'd like to see the the text elements within the editable fields rendered a bit differently.  

Specifically, I'd like to see a thin grey line (identical in thickness and grey-shade to the field divider lines) drawn like a button outline around the text string, with identical radiusing at the corners to our other large buttons.  

There should be a minimum number of white pixels between the field text string and the left hand side and right hand side of this outline, so that the field text doesn't touch right up against the grey outline.  There should also be a small white gap above and below the outline so that the outline doesn't touch right up against the field divider lines.  Careful positioning is needed to get this right.

Is this technically feasible?!?

**Comment by whitemx** [comment]
Hi Steve,

Yes that's possible, I'll slate this for 1.2

Matt

**Comment by sives** [comment]
OK, sounds good

On Wed, Jan 23, 2013 at 9:36 AM, Matt White notifications@github.comwrote:

> Hi Steve,
> 
> Yes that's possible, I'll slate this for 1.2
> 
> Matt
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/unplugged/unplugged-controls/issues/98#issuecomment-12587938.

## 

_Stephen Ives_ / Director
*www.hoverkey.com
*Strong mobile security without passwords

**Comment by sives** [comment]
Steve needs to test this and Jack Herbert needs to style this.
